---
permalink: linux-administration/concept_host_filespec_information_for_a_particular_volume.html 
sidebar: sidebar 
keywords: snap, snapdrive, filespec, volume, host, lun 
summary: SnapDrive for UNIX as part of volume restore preview レポートには、 LUN マッピング情報が表示されます。この情報はチェックに関連して表示され、通常のファイルは復元されます。特定のボリューム上の LUN に基づくすべてのホストファイルを検出すると時間がかかり、ボリュームのリストアプロセスの速度が低下します。 
---
= 特定のボリュームのホスト・ファイル仕様情報
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX as part of volume restore preview レポートには、 LUN マッピング情報が表示されます。この情報はチェックに関連して表示され、通常のファイルは復元されます。特定のボリューム上の LUN に基づくすべてのホストファイルを検出すると時間がかかり、ボリュームのリストアプロセスの速度が低下します。

特定のストレージ・システム・ボリュームにマッピングされたローカル・ホストのホスト・ファイル仕様情報を確認するには、 SnapDrive storage show -filol <full-volume-name>` を使用します。この例を次に示します。

[listing]
----
#snapdrive storage show -filervol bart:/vol/volusecase2

Connected LUNs and devices:

 device filename        adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdg                  -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun5          -

Host devices and file systems:

dg: vbsrfs_1_SdDg               dgtype lvm
hostvol: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv        state: AVAIL
fs: /dev/mapper/vbsrfs_1_SdDg-vbsrfs_1_SdHv     mount point: /mnt/vbsrfs_1 (persistent) fstype ext3

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbe                 -     P       100m    iscsi   online   No     bart:/vol/volusecase1/lun9_0        -
/dev/sdbf                 -     P       100m    iscsi   online   No     bart:/vol/volusecase2/lun4_0        -

raw device: /dev/sdbr1  mount point: /mnt/fs11 (persistent) fstype ext3

 device filename     adapter path    size    proto   state   clone   lun path           backing snapshot
----------------        ------- ----    ----    -----   -----   -----   --------                        ----------------
/dev/sdbr                 -     P       200m    iscsi   online   No     bart:/vol/volusecase2/fs11_SdLun    -

NFS device: bart:/vol/volusecase1        mount point: /mnt/volusecase1 (non-persistent)

LUNs not connected to this host:

 lun path                                           size   state
 -----------------------------               ------ ------
 bart:/vol/volusecase2/lunotherhost 20m   online
----