---
permalink: linux-administration/concept_error_message_format.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message, format 
summary: エラーメッセージの形式は、エラーの原因を特定するのに役立ちます。 
---
= エラーメッセージの形式
:icons: font
:imagesdir: ../media/


[role="lead"]
エラーメッセージの形式は、エラーの原因を特定するのに役立ちます。

SnapDrive for UNIX は、標準のエラーコード情報を返します。これにより、初期エラー状態の原因となった項目のより具体的な概要が提供されます。SnapDrive for UNIX のエラー・メッセージは、次の形式に準拠しています。

「コードメッセージ ID エラータイプ : メッセージテキスト」を無効にします

* `_return code_` -- エラー状態の基本的な原因を示す終了ステータス値にリンクされた UNIX エラーメッセージ ID の SnapDrive 。
* `_message-ID_` -- エラーを発生させた特定のコードを特定するためにネットアップテクニカルサポートが使用する一意の識別子。ネットアップテクニカルサポートに問い合わせる必要がある場合は、エラーメッセージに付随するメッセージ ID を記録しておくことを推奨します。
* `_error type_` -- SnapDrive for UNIX が検出したエラーの種類を指定します戻り値は次のとおりです。
+
** `_Warning_` -- SnapDrive for UNIX はコマンドを実行しましたが ' 注意が必要な状態についての警告を発行しました
** `_command_` -- SnapDrive for UNIX はコマンドラインのエラーのためにコマンドを実行できませんでした。コマンドラインの形式と変数が正しいことを確認してください。
** `_Admin_` -- SnapDrive for UNIX はシステム構成の非互換性のためにコマンドを実行できませんでしたシステム管理者に問い合わせて、設定パラメータを確認してください。
** `_Fatal_ ` -- SnapDrive for UNIX は予期しない状態のためにコマンドを実行できませんでした致命的なエラーはまれです。致命的なエラーが発生し、問題の解決に問題が生じた場合は、ネットアップのテクニカルサポートにお問い合わせください。


* `_message text_` -- エラーを説明する情報。このテキストには、エラーの詳細を示すために別のコンポーネントからの情報が含まれている場合があります。たとえば、ディスクグループなどのコマンドライン引数がない場合、何が見つからないかを示すエラーメッセージが表示されます。または、 SnapDrive for UNIX がストレージ・システムの制御に使用する Manage ONTAP API では、エラーの説明に役立つ追加テキストが提供されることがあります。この場合、 SnapDrive for UNIX の基本的なエラーメッセージに従います。

