---
permalink: linux-administration/concept_application_consistentsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, copy, application 
summary: アプリケーションと整合性のある Snapshot コピーを作成するには、 Snapshot 処理の前にアプリケーションを停止する必要があります。 
---
= アプリケーションと整合性のある Snapshot コピー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アプリケーションと整合性のある Snapshot コピーを作成するには、 Snapshot 処理の前にアプリケーションを停止する必要があります。

Snapshot コピーがアプリケーションと整合性のあるものであることを確認するには、 Snapshot コピーを作成する前に、アプリケーションを停止するか休止する必要がある場合があります。データベースのホットバックアップ機能は DBMS で使用される方法に依存するため、データベースファイルへの I/O を常に停止するわけではありません。

アプリケーションがトランザクションを完了せず、データをストレージシステムに書き込んでいない場合、作成された Snapshot コピーがアプリケーションと整合性のない状態になる可能性があります。


NOTE: crash-consistent Snapshot コピーからアプリケーションがリカバリ可能であれば、コピーを停止する必要はありません。アプリケーションのマニュアルを参照してください。アプリケーションと整合性のある Snapshot コピーの作成に関する詳細については、を参照してください。

ホストボリューム、 LUN 、または NFS ディレクトリツリーを追加または削除するとき、またはホストボリュームまたはファイルシステムのサイズを変更するときは、必ず新しい Snapshot コピーを作成してください。これにより、新しく設定したディスクグループの整合性のあるコピーが作成され、ディスクグループのリストアが必要になった場合に使用できるようになります。
