---
permalink: linux-administration/concept_guidelines_for_thesnapdrive_storagedisconnectcommand.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, disconnect, command, guidelines 
summary: SnapDrive storage disconnect コマンドを使用する場合は、次のガイドラインに従います。 
---
= SnapDrive storage disconnect コマンドのガイドラインです
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive storage disconnect コマンドを使用する場合は、次のガイドラインに従ってください。

* ファイルシステムを切断すると、 SnapDrive for UNIX では必ずマウントポイントが削除されます。
+
Linux ホストでは、複数のファイルシステムを単一のマウントポイントに接続できます。ただし、 SnapDrive for UNIX の場合、ファイルシステムごとに一意のマウントポイントが必要です。単一のマウントポイントに接続されているファイル・システムを切断するために SnapDrive storage disconnect コマンドを使用すると ' 失敗します

* -lun' オプションを使用して ' ホスト・ディスク・グループまたはファイル・システムのいずれかのメンバーである LUN の名前を指定すると ' SnapDrive storage disconnect コマンドは失敗します
* -lun' オプションを使用 SnapDrive して ' ホスト上のマルチパス・ソフトウェアによって検出されない LUN の名前を指定すると 'lun disconnect コマンドは失敗します



NOTE: SnapDrive 5.2 for UNIX より前のリリースでは、 RDM LUN の使用中に SnapDrive storage disconnect コマンドが失敗し、マッピング igroup に World Wide Port Name （ WWPN ；ワールドワイドポート名）が 3 つ以上含まれている場合。
