---
permalink: linux-administration/reference_error_message_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message, value, common 
summary: SnapDrive for UNIX を使用しているときに表示される一般的なエラーメッセージとその対処方法を理解しておくと役立ちます。 
---
= エラーメッセージの値
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX を使用しているときに表示される一般的なエラーメッセージとその対処方法を理解しておくと役立ちます。

次の表に、 SnapDrive for UNIX の使用時に発生する可能性がある代表的なエラーに関する詳細情報を示します。

[cols="15,20,15,25,40"]
|===
| エラーコード | リターンコード | を入力します | メッセージ | 解決策 


 a| 
「 0000-001` 」
 a| 
該当なし
 a| 
管理
 a| 
「ストレージシステム <storage-system-name> に対して設定されました。SnapDrive config delete mgmtpath コマンドを使用してこれを削除し、再試行してください。
 a| 
ストレージシステムを削除する前に、 SnapDrive config delete -mgmtpath コマンドを使用して、ストレージシステムに設定されている管理パスを削除します。



 a| 
「 0001 」 ～ 「 242 」
 a| 
該当なし
 a| 
管理
 a| 
HTTPS を使用してストレージ・システムに接続できない： 10.72.197.21310.72.197.213 が有効なストレージシステムの名前 / アドレスであることを確認します。 設定するストレージシステムが Data ONTAP 7-Mode で実行されている場合は、信頼されたホスト（ options trusted.hosts ）にホストを追加し、ストレージシステム 10.72.197.213 で SSL を有効にするか、 http を使用して通信を開始し、 SnapDrive デーモンを再起動するように snapdrive.conf を変更します。設定するストレージシステムが clustered Data ONTAP 上で実行されている場合には、 SVM 名が SVM の管理 LIF の IP アドレスにマッピングされていることを確認してください
 a| 
次の条件を確認します。

* 接続しているストレージシステムが有効なストレージシステムであることを確認してください。
* 設定しようとしているストレージシステムが Data ONTAP 7-Mode で実行されている場合は、信頼できるホストに同じ SSL を追加し、ストレージシステムで SSL を有効にするか、「 snapdrive.conf 」ファイルを変更して通信に HTTP を使用するようにしてから、 SnapDrive デーモンを再起動します。
* 設定するストレージシステムが clustered Data ONTAP で実行されている場合は、 SVM 名が SVM の管理論理インターフェイス（ LIF ）の IP アドレスにマッピングされていることを確認してください。




 a| 
「 0003-004 」
 a| 
該当なし
 a| 
管理
 a| 
' ゲスト OS からストレージシステム <storage-system-name> 上の LUN <lun-name> のデポートに失敗しました。理由： CoreOS からマッピングデバイス情報が入力されていません
 a| 
これは、ゲスト OS で SnapDrive の snap disconnect 操作を実行した場合に発生します。

ESX サーバに RDM LUN マッピングがあるか、または ESX サーバに古い RDM エントリがあるかを確認します。

ESX サーバおよびゲストオペレーティングシステムで RDM マッピングを手動で削除します。



 a| 
「 0001-019 」
 a| 
3.
 a| 
コマンドを実行します
 a| 
無効なコマンドライン -- 重複したファイル指定 : <dg1/vol2 と dg1/vol2
 a| 
これは、実行するコマンドに同じホストボリューム上に複数のホストエンティティがある場合に発生します。

たとえば、ホストボリュームとファイルシステムは同じホストボリュームに明示的に指定されています。

次の手順を実行します。

. ホストエンティティの重複するインスタンスをすべて削除します。
. コマンドを再度実行します。




 a| 
「 0001 」 ～ 「 23 」
 a| 
11.
 a| 
管理
 a| 
'DG1 ディスク・グループ内のすべての LUN を検出できませんデバイスが応答していません : DG1 ストレージ・システム上の LUN ステータスを確認し 'LUN を必要に応じてオンラインにするか ' 信頼できるホスト（ options trusted.hosts ）にホストを追加してストレージ・システム上で SSL を有効にするか 'snapdrive.conf を変更して（ http/https ）ストレージ・システム通信に使用し ' SnapDrive デーモンを再起動してください
 a| 
これは、デバイスの SCSI 照会に失敗した場合に発生します。デバイスの SCSI 照会に複数の理由で失敗する可能性があります。

次の手順を実行します。

. device-retries 設定変数を大きい値に設定します。
+
たとえば、 10 に設定し（デフォルト値は 3 ）、コマンドを再度実行します。

. デバイスに関する情報を取得するには、 SnapDrive storage show コマンドに「 -all 」オプションを指定して使用します。
. FC サービスまたは iSCSI サービスがストレージシステムで実行されているかどうかを確認します。
+
サポートされていない場合は、ストレージ管理者に問い合わせて、ストレージシステムをオンラインにします。

. FC サービスまたは iSCSI サービスがホスト上で稼働しているかどうかを確認します。


上記の解決方法で問題が解決しない場合は、テクニカルサポートにお問い合わせください。



 a| 
「 0001 」 ～ 「 395 」
 a| 
該当なし
 a| 
管理
 a| 
「このホストには HBA はありません！
 a| 
これは、ホストシステムに多数の LUN が接続されている場合に発生します。

「 napdrive.conf 」ファイルで変数「 _enable-fcp-cache-」 が ON に設定されているかどうかを確認します。



 a| 
「 0001-389` 」
 a| 
該当なし
 a| 
管理
 a| 
HBA アシスタント linuxfcp の HBA タイプを取得できません
 a| 
これは、ホストシステムに多数の LUN が接続されている場合に発生します。

「 napdrive.conf 」ファイルで変数「 _enable-fcp-cache-」 が ON に設定されているかどうかを確認します。



 a| 
「 0001-389` 」
 a| 
該当なし
 a| 
管理
 a| 
HBA アシスタントの vmwarefcp の HBA タイプを取得できません
 a| 
次の条件を確認する必要があります。

* ストレージを作成する前に、コマンドを使用して仮想インターフェイスを設定したかどうかを確認してください。


'*SnapDrive config set__ viadmin <user><VIRTUE_interface_IP または NAME>_*'

* 仮想インターフェイスにストレージシステムが存在することを確認します。同じエラーメッセージが表示される場合は、ストレージ作成処理を正常に実行するために、 SnapDrive for UNIX を再起動します。
* に記載されている Virtual Storage Console の構成要件を満たしているかどうかを確認します link:https://www.netapp.com/pdf.html?item=/media/7350-ds-3057.pdf["NetApp Virtual Storage Console for VMware vSphere"]




 a| 
「 0001 」 ～ 「 682 」
 a| 
該当なし
 a| 
管理
 a| 
' 新しい LUN のホスト準備に失敗しました : この機能チェックコントローラはサポートされていません
 a| 
SnapDrive 処理が成功するようにするには、コマンドをもう一度実行します。



 a| 
「 0001-859` 」
 a| 
該当なし
 a| 
管理
 a| 
' いずれのホストのインタフェースにも ' ストレージ・システム上のディレクトリ < ディレクトリ名 > にアクセスするための NFS 権限がありません
 a| 
'napdrive.conf' ファイルで '_check-export-permission-nfs-clone_' 構成変数が 'off' に設定されていることを確認します



 a| 
「 0002 - 253 」
 a| 
 a| 
管理
 a| 
Flex クローンの作成に失敗しました
 a| 
ストレージシステム側のエラーです。トラブルシューティングを行うには、 sd-trace.log とストレージシステムのログを収集してください。



 a| 
「 0002 」 ～ 「 264 」
 a| 
 a| 
管理
 a| 
FlexClone はファイラー <filer name> ではサポートされていません
 a| 
FlexClone は、現在の Data ONTAP バージョンのストレージシステムではサポートされていません。ストレージシステムの Data ONTAP バージョンを 7.0 以降にアップグレードしてから、もう一度コマンドを実行してください。



 a| 
000-265`
 a| 
 a| 
管理
 a| 
ファイラー <filername> で flex_clone ライセンスを確認できません
 a| 
ストレージシステム側のエラーです。sd-trace.log とストレージシステムログを収集してトラブルシューティングを行います。



 a| 
「 0002 」 ～ 「 266 」
 a| 
該当なし
 a| 
管理
 a| 
「 FlexClone はファイラー <filername> でライセンスされていません
 a| 
ストレージシステムに FlexClone のライセンスがありません。ストレージシステムに FlexClone ライセンスを追加してから、コマンドを再試行します。



 a| 
「 0002 - 267 」
 a| 
該当なし
 a| 
管理
 a| 
FlexClone はルート・ボリューム <volume-name>` ではサポートされていません
 a| 
ルートボリュームに FlexClone を作成することはできません。



 a| 
「 0002 」 ～ 「 270 」
 a| 
該当なし
 a| 
管理
 a| 
アグリゲートの空き領域 <aggregate-name> は、ディスクグループ / FlexClone メタデータに必要な <size> MB （メガバイト）より小さい値です
 a| 
. FlexClone を使用して raw LUN に接続する場合、アグリゲートに 2MB の空きスペースが必要です。
. 手順 1 および 2 に従ってアグリゲートのスペースを解放してから、コマンドを再試行します。




 a| 
「 0002 」 ～ 「 332 」
 a| 
該当なし
 a| 
管理
 a| 
'D.snapshot.Restore access denied on qtree storage_array1 ： /vol/vol1/qtree1 for user lnx197-142\john
 a| 
必要な機能をユーザに付与するには、 Operations Manager 管理者にお問い合わせください。



 a| 
「 0002 ～ 364 」
 a| 
該当なし
 a| 
管理
 a| 
'dfm に連絡できません： lnx197-146 ユーザー名またはパスワードを変更してください
 a| 
SD-admin ユーザーのユーザー名とパスワードを確認して修正します。



 a| 
「 0002 」 ～ 「 268 」
 a| 
該当なし
 a| 
管理
 a| 
'< ボリューム名 > はフレキシブル・ボリュームではありません
 a| 
トラディショナルボリュームでは FlexClone を作成できません。



 a| 
「 0003-003 」
 a| 
 a| 
管理
 a| 
. 'LUN <lun_name> をストレージシステム <storage_name> のゲスト OS にエクスポートできませんでした
+
....
or
....

 a| 
* ESX サーバ（または）の古い RDM エントリに RDM LUN マッピングが含まれていないかどうかを確認します。
* ESX サーバおよびゲストオペレーティングシステムで RDM マッピングを手動で削除します。




 a| 
「 0003-012 」
 a| 
 a| 
管理
 a| 
Virtual Interface Server Win2k3-325238 にアクセスできません
 a| 
ホスト / ゲスト OS に対して NIS がに設定されていません。

/etc/hosts' にあるファイルに ' 名前と IP マッピングを指定する必要があります

たとえば '# cat /etc/hosts10.72.225.238 win2k3-225-238.eng.org.com Win2k3-225-238' のようになります



 a| 
「 0001-552 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
' 有効なボリュームクローンまたは LUN クローンではありません
 a| 
トラディショナルボリュームの場合、クローンスプリットは作成できません。



 a| 
「 0001-553 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「 <filer-Name> 」に十分なストレージ・スペースがないため、「 FS-Name 」を分割できません
 a| 
クローンスプリットはスプリット処理を続行し、ストレージシステムで使用できるストレージスペースが不足したために突然クローンスプリットが停止します。



 a| 
「 0003-002 」と入力します
 a| 
 a| 
コマンドを実行します
 a| 
「これ以上 LUN をゲスト OS にエクスポートすることはできません。
 a| 
ESX サーバでコントローラに対してサポートされるデバイスの数が上限に達したため、ゲストオペレーティングシステムのコントローラを追加する必要があります。

* 注： * ESX サーバは、ゲスト OS あたりの最大コントローラ数を 4 に制限しています。



 a| 
「 9000-023`
 a| 
1.
 a| 
コマンドを実行します
 a| 
'Keyword -lun' の引数がありません
 a| 
このエラーは '-lun' キーワードを指定したコマンドに '_lun_name_' 引数がない場合に発生します

対処方法：次のいずれかを実行します。

. コマンドの引数に '-lun' キーワードを指定して '_lun_name_' を指定します
. SnapDrive for UNIX のヘルプ・メッセージを確認します




 a| 
「 0001 」 ～ 「 028 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
ファイルシステム /mnt/qa/dg4/vol1> は、 SnapDrive で管理されないタイプ（ HFS ）です。リクエストを再送信して、ファイルシステム </mnt/qa/dg4/vol1> を終了してください
 a| 
このエラーは、サポートされていないファイルシステムタイプがコマンドの一部である場合に発生します。

操作 : ファイルシステムタイプを除外または更新してから、コマンドをもう一度使用します。

ソフトウェアの互換性に関する最新情報については、 Interoperability Matrix を参照してください。



 a| 
「 9000-030`
 a| 
1.
 a| 
コマンドを実行します
 a| 
-lun は他のキーワードと組み合わせて使用することはできません
 a| 
このエラーは '-lun' キーワードと '-fs' または '-dg キーワードを組み合わせた場合に発生しますこれは構文エラーであり、コマンドの使用方法が無効であることを示しています。

操作：コマンドを再度実行するには、「 -lun 」キーワードを指定する必要があります。



 a| 
「 0001 」 ～ 「 034 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
'`mount failed: mount: <device name> は有効なブロックデバイスではありません
 a| 
このエラーは、クローニングされた LUN が、 Snapshot コピー内の同じファイル仕様にすでに接続されている場合に、 SnapDrive snap restore コマンドを実行しようとしたときに発生します。

コマンドは失敗します。これは、クローニングされた LUN を削除すると、 iSCSI デーモンがリストアされた LUN のデバイスエントリを再マッピングするためです。

対処方法：次のいずれかを実行します。

. SnapDrive snap restore コマンドを再度実行します。
. 元の LUN の Snapshot コピーをリストアする前に、接続されている LUN （ Snapshot コピーと同じファイル仕様にマウントされている場合）を削除します。




 a| 
0001-046 および 0001-047
 a| 
1.
 a| 
コマンドを実行します
 a| 
無効なスナップショット名： /vol/vol1/no_filer_pre fix> または無効なスナップショット名： no_dlong _filername - ファイラーボリューム名がありません
 a| 
無効な Snapshot 名で Snapshot 処理が試行されたコマンドで、構文エラーが発生しています。

What to do ：次の手順を実行します。

. SnapDrive の Snapshot コピーのリストを取得するには、 lun snap list -ffiler <filer-volume -name> コマンドを使用します。
. long_snap_name 引数を指定してコマンドを実行します




 a| 
「 9000-047 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
`s 与えられる 1 つ以上の snapname 引数
 a| 
SnapDrive for UNIX では、 Snapshot 処理を実行するために、コマンドラインで複数の Snapshot 名を指定することはできません。

What to do ： 1 つの Snapshot 名だけを指定してもう一度コマンドを実行します。



 a| 
「 9000-049` 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
dg と -vg は併用できません
 a| 
このエラーは '-dg' キーワードと -vg` キーワードを組み合わせると発生しますこれは構文エラーであり、コマンドの使用方法が無効であることを示しています。

操作 : コマンドを実行するには '-dg または --vg キーワードを指定します



 a| 
「 9000-050` 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
「 -lvol 」と「 -hostvol 」は併用できません
 a| 
このエラーは、「 -lvol 」キーワードと「 -hostvol 」キーワードを組み合わせると発生します。これは構文エラーであり、コマンドの使用方法が無効であることを示しています。What to do ：次の手順を実行します。

. コマンド・ラインで '-lvol' オプションを -hostvol' オプションに変更するか ' またはその逆に変更します
. コマンドを実行します。




 a| 
「 9000-057
 a| 
1.
 a| 
コマンドを実行します
 a| 
`m ising required-snapname argument `
 a| 
この構文エラーは、 snap_name 引数を指定しないと Snapshot 処理が試行されるコマンドの使用が無効であることを示します。

What to do ：適切な Snapshot 名を指定してコマンドを実行します。



 a| 
「 0001 」 ～ 「 67 」
 a| 
6.
 a| 
コマンドを実行します
 a| 
'Snapshothourly.0 のスナップショットは、 SnapDrive によって作成されませんでした
 a| 
Data ONTAP によって 1 時間ごとに作成された自動 Snapshot コピーです。



 a| 
0001 ～ 092`
 a| 
6.
 a| 
コマンドを実行します
 a| 
'snapshot-<NON_EXistent 24965> は、 fileervol exocet: </vol/vol1/vol>` に存在しません
 a| 
指定した Snapshot コピーがストレージシステム上で見つかりませんでした。What to do ： SnapDrive snap list コマンドを使用して、ストレージ・システムに存在する Snapshot コピーを検索します。



 a| 
「 0001-099 」
 a| 
10.
 a| 
管理
 a| 
無効な Snapshot 名： <exocet: /vol/vol2/dbvol: New snapname> がストレージシステムボリューム名 <exocet: /vol/vol1/vol>` と一致しません
 a| 
無効な Snapshot 名で Snapshot 処理が試行されるコマンドの使用を示す構文エラーです。

What to do ：次の手順を実行します。

. SnapDrive の Snapshot コピーのリストを表示するには、 lun snap list -fer_<filer -volume -name_` コマンドを使用します。
. SnapDrive for UNIX で認定されている正しい形式の Snapshot 名を使用してコマンドを実行します。修飾された形式は '_long_snap_name_` と '_short_snap_name_` です




 a| 
「 0001 」 ～ 「 122 」
 a| 
6.
 a| 
管理
 a| 
'Failed to get snapshot list on filer <exocet> ：指定されたボリュームは存在しません
 a| 
このエラーは、指定されたストレージシステム（ファイラー）ボリュームが存在しない場合に発生します。

What to do ：次の手順を実行します。

. ストレージ管理者に問い合わせて、有効なストレージシステムボリュームのリストを入手してください。
. 有効なストレージ・システム・ボリューム名を指定してコマンドを実行します。




 a| 
「 0001 」 ～ 「 124 」
 a| 
111
 a| 
管理
 a| 
` Filer <exocet>: LUN クローンで <snap_delete_multi_inuse_24374> を削除できませんでした
 a| 
LUN クローンが存在するため、指定された Snapshot コピーの「 Snapshotdelete 」操作が失敗しました。

What to do ：次の手順を実行します。

. SnapDrive storage show コマンドに「 -all 」オプションを指定して、 Snapshot コピー（元の Snapshot コピーの出力に含まれる）の LUN クローンを検索します。
. LUN をクローンからスプリットする場合は、ストレージ管理者に問い合わせてください。
. コマンドを再度実行します。




 a| 
「 0001 」 ～ 「 155 」
 a| 
4.
 a| 
コマンドを実行します
 a| 
スナップショット <DUP_snapname23980> は、 <exocet:/vol/vol1/vol> にすでに存在します。既存のスナップショットを上書きするには '-f (force) フラグを使用してください
 a| 
このエラーは、コマンドで使用されている Snapshot コピー名がすでに存在する場合に発生します。

対処方法：次のいずれかを実行します。

. 別の Snapshot 名でコマンドを再度実行します。
. 「 -f 」（ force ）フラグを指定してコマンドを再度実行し、既存の Snapshot コピーを上書きします。




 a| 
「 0001-158` 」
 a| 
84
 a| 
コマンドを実行します
 a| 
「 <snapshotexocet:/vol/vo L1 ： overwrite-noforce_25 078> が作成されたため、 `iskgroup の設定が変更されました。hostvol /dev/dg3/Vol4 を削除しました。 '-f ' （ force ）フラグを使用して警告を無視し、リストアを完了してください
 a| 
ディスクグループには複数の LUN を含めることができ、ディスクグループの構成を変更すると、このエラーが発生します。たとえば、 Snapshot コピーを作成する場合、ディスクグループの LUN 数は X となり、コピーの作成後に、ディスクグループの LUN 数は X + Y になります。

何をするか : コマンドは、「 -f 」（ force ）フラグを付けて再度使用してください。



 a| 
「 0001 」 ～ 「 185 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「 storage show failed ： no NetApp devices to show or enable SSL on the filers or retry after changing snapdrive.conf to use http for filercommunication 」というエラーメッセージが表示されます
 a| 
この問題は、次の理由で発生する可能性があります。

ホスト上の iSCSI デーモンまたは FC サービスが停止しているか ' または動作不良の場合 ' ホスト上に構成されている SnapDrive があっても 'lun storage show -all コマンドは失敗します

What to do ：正常に機能しない iSCSI サービスまたは FC サービスを解決します。

LUN が構成されているストレージシステムが停止しているか、リブートを実行中である。

What to do ： LUN が起動するまで待ちます。

コンフィギュレーション変数「 _usehttps-to-filer_」 に設定された値は、サポートされていない設定である可能性があります。

What to do ：次の手順を実行します。

. 「 lun lun lun show all 」コマンドを使用して、ホストにマッピングされた LUN があるかどうかを確認します。
. ホストに LUN がマッピングされている場合は、エラーメッセージに記載されている手順に従います。


コンフィギュレーション変数「 _usehttps-to-filer_」 の値を変更します（値が「 off 」の場合は「 on 」に、値が「 on 」の場合は「 off 」に変更します）。



 a| 
「 0001 」 ～ 「 226 」
 a| 
3.
 a| 
コマンドを実行します
 a| 
「 snap create 」を使用するには、すべてのファイル仕様にアクセスできる必要があります。以下のファイル仕様にアクセスできないことを確認してください。ファイルシステム : /mnt/qa/dg1/vol3>
 a| 
このエラーは、指定したホストエンティティが存在しない場合に発生します。

操作： SnapDrive storage show コマンドを再び -all オプションとともに使用して ' ホスト上に存在するホスト・エンティティを検索します



 a| 
「 0001 」 ～ 「 242 」
 a| 
18
 a| 
管理
 a| 
'Unable to connect to filer:<filername>`
 a| 
SnapDrive for UNIX は、セキュアな HTTP プロトコルを使用してストレージシステムへの接続を試みます。このエラーは、ホストがストレージシステムに接続できない場合に発生することがあります。

What to do ：次の手順を実行します。

. ネットワークの問題：
+
.. nslookup コマンドを使用して、ホストを介して動作するストレージ・システムの DNS 名前解決を確認します。
.. DNS サーバが存在しない場合は、そのサーバにストレージシステムを追加します。
+
ストレージシステムへの接続には、ホスト名の代わりに IP アドレスを使用することもできます。



. ストレージシステムの構成：
+
.. SnapDrive for UNIX を使用するには、セキュアな HTTP アクセスのライセンスキーが必要です。
.. ライセンスキーを設定したら、 Web ブラウザからストレージシステムにアクセスできるかどうかを確認します。


. 手順 1 、手順 2 、またはその両方を実行したあとにコマンドを実行します。




 a| 
「 0001-243 」と表示されます
 a| 
10.
 a| 
コマンドを実行します
 a| 
Dg 名が無効です : <SDP_dg1>
 a| 
このエラーは、ディスクグループがホストに存在しないためにコマンドが失敗した場合に発生します。たとえば '`_sdu_dg1_` はホストに存在しません

What to do ：次の手順を実行します。

. すべてのディスク・グループ名を取得するには、 SnapDrive storage show -all コマンドを使用します。
. 正しいディスクグループ名を指定してコマンドを再度実行します。




 a| 
「 0001 」 ～ 「 246
 a| 
10.
 a| 
コマンドを実行します
 a| 
無効なホストボリューム名： /mnt/qa/DG2/BADFS > 、有効な形式は <vgname/ hostvolname> 、つまり <mygroup/v2>> です
 a| 
対処方法：ホスト・ボリューム名に適切な形式を使用して、もう一度コマンドを実行します。「 vgname/ hostvolName 」



 a| 
「 0001 ～ 360 」
 a| 
34
 a| 
管理
 a| 
'LUN の作成に失敗しました /vol/badvol1/nanehp13_unnewDg_fve_sdLun> オン・ファイラー <exocet> ：このボリュームはありません
 a| 
このエラーは、指定したパスに存在しないストレージシステムボリュームが含まれている場合に発生します。

What to do ：ストレージ管理者に問い合わせて、使用可能なストレージシステムボリュームのリストを入手してください。



 a| 
「 0001 」 ～ 「 372 」
 a| 
58
 a| 
コマンドを実行します
 a| 
「 + 不正な LUN 名： +```/vol/vol1/SCE_lun2a> - format not recognized 」というエラーが表示されます
 a| 
このエラーは、コマンドで指定した LUN 名が、 SnapDrive for UNIX でサポートされる事前定義された形式に従っていない場合に発生します。SnapDrive for UNIX では、事前定義された「 <filer-name ： /vol/<volname>/<lun-name> 」の形式で LUN 名を指定する必要があります

What to do ：次の手順を実行します。

. SnapDrive ヘルプのコマンドを使用して、 SnapDrive for UNIX でサポートされる LUN 名の事前定義された形式を確認します。
. コマンドを再度実行します。




 a| 
「 0001-373`
 a| 
6.
 a| 
コマンドを実行します
 a| 
必要な 1 つの LUN が見つかりません : exocet: /vol/vol1/NotARealLun>`
 a| 
このエラーは、指定した LUN がストレージシステムで見つからない場合に発生します。

対処方法：次のいずれかを実行します。

. ホストに接続 SnapDrive されている LUN SnapDrive を表示するには、 lun storage show -dev コマンドまたは lun storage show -all コマンドを使用します。
. ストレージシステム上の LUN の全リストを表示するには、ストレージ管理者に問い合わせて、ストレージシステムから lun show コマンドの出力を取得してください。




 a| 
「 0001 」 ～ 「 377 」
 a| 
43
 a| 
コマンドを実行します
 a| 
「ディスクグループ名 < 名前 > は既に使用されているか、別のエンティティと競合しています。
 a| 
このエラーは、ディスクグループ名がすでに使用されているか、別のエンティティと競合している場合に発生します。対処方法：次のいずれかを実行します。

. -autorname' オプションを指定してコマンドを実行します
. SnapDrive storage show コマンドに「 -all 」オプションを指定して、ホストが使用している名前を検索します。ホストが使用していない別の名前を指定してコマンドを実行します。




 a| 
「 0001 」 ～ 「 380 」
 a| 
43
 a| 
コマンドを実行します
 a| 
ホストボリューム名 <dg3/vol1> はすでに使用されているか、別のエンティティと競合しています
 a| 
このエラーは、ホストボリューム名がすでに使用されているか別のエンティティと競合している場合に発生します

対処方法：次のいずれかを実行します。

. -autorname' オプションを指定してコマンドを実行します
. SnapDrive storage show コマンドに「 -all 」オプションを指定して、ホストが使用している名前を検索します。ホストが使用していない別の名前を指定してコマンドを実行します。




 a| 
「 0001 」 ～ 「 417 」
 a| 
51
 a| 
コマンドを実行します
 a| 
次の名前は既に使用されています : <mydg1> 。他の名前を指定してください
 a| 
対処方法：次のいずれかを実行します。

. コマンドをもう一度 -autorname' オプションを指定して実行します
. SnapDrive storage show -all コマンドを使用して、ホスト上に存在する名前を検索します。ホストで使用していない別の名前を明示的に指定するには、コマンドをもう一度実行します。




 a| 
「 0001-430 」
 a| 
51
 a| 
コマンドを実行します
 a| 
dg/vg DG と -lvol/hostvol dg/vol の両方を指定することはできません
 a| 
コマンドの使用方法が無効であることを示す構文エラーです。コマンド・ラインには '-dg/vg` キーワードまたは -lvol/hostvol キーワードのいずれかを指定できますが ' 両方を指定することはできません

操作 : コマンドを実行するには '-dg/vg' または --lvol/hostvol' キーワードだけを指定します



 a| 
「 0001 」 ～ 「 434 」
 a| 
6.
 a| 
コマンドを実行します
 a| 
「 Snapshot の追加： /vol/vol1/vol1 ： not_E IST がストレージボリュームの exocet ： /vol/vol1/vol1 に存在しません
 a| 
このエラーは、指定した Snapshot コピーがストレージシステムで見つからない場合に発生します。

What to do ： SnapDrive snap list コマンドを使用して、ストレージ・システムに存在する Snapshot コピーを検索します。



 a| 
「 0001 」 ～ 「 435 」
 a| 
3.
 a| 
コマンドを実行します
 a| 
` すべてのホスト・ボリュームまたはすべてのファイル・システムをコマンド・ラインで指定するか 'autoconfigure オプションを指定する必要がありますコマンドラインで次の名前が見つかりませんでしたが、スナップショット <snap2_5VG_SINGLElun_REMOT> で見つかりました。ホストボリューム： <dg3/vol2 > ファイルシステム： /mnt/qa/dg3/vol2
 a| 
指定したディスクグループには複数のホストボリュームまたはファイルシステムがありますが、コマンドでは完全なセットは示されません。

対処方法：次のいずれかを実行します。

. -autodexpand オプションを指定してコマンドを再発行します
. SnapDrive snap show コマンドを使用して ' ホスト・ボリュームとファイル・システムの全リストを検索しますすべてのホストボリュームまたはファイルシステムを指定してコマンドを実行します。




 a| 
「 0001-440 」
 a| 
6.
 a| 
コマンドを実行します
 a| 
「スナップショット snap2_5VG_SINGLELUN_REMOTE 」にはディスクグループ「 dbad 」が含まれていません
 a| 
このエラーは、指定したディスクグループが指定した Snapshot コピーに含まれていない場合に発生します。

What to do ：指定したディスクグループに Snapshot コピーがあるかどうかを確認するには、次のいずれかを実行します。

. SnapDrive snap list コマンドを使用して、ストレージ・システム内の Snapshot コピーを検索します。
. SnapDrive snap show コマンドを使用して、 Snapshot コピー内に存在するディスク・グループ、ホスト・ボリューム、ファイル・システム、または LUN を検索します。
. ディスクグループの Snapshot コピーが存在する場合は、 Snapshot 名を指定してコマンドを実行します。




 a| 
「 0001-442` 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
「 1 つのスナップ接続ソース <src> に指定された宛先 <dis> と <dis1> よりも大きい値です。別のコマンドを使用して再試行してください
 a| 
操作 : 個別の SnapDrive snap connect コマンドを実行して ' 新しいターゲット・ディスク・グループ名（ snap connect コマンドの一部）が ' 同じ SnapDrive snap connect コマンドの他のディスク・グループ・ユニットの一部であるものと同じではないようにします



 a| 
「 0001 」 ～ 「 465 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
次のファイル指定は存在しないため削除できません : ディスクグループ : <nanehp13_dg1>
 a| 
指定したディスクグループがホストに存在しないため、指定したディスクグループの削除に失敗しました。

What to do ： all オプションを指定して SnapDrive storage show コマンドを使用し、ホスト上のエンティティのリストを表示します。



 a| 
「 0001 」 ～ 「 476 」
 a| 
該当なし
 a| 
管理
 a| 
'Unable to discover the device associated with <long LUN name> マルチパスを使用している場合、マルチパス構成にエラーがある可能性があります。設定を確認してから、もう一度やり直してください
 a| 
この失敗には多くの原因が考えられます。

* 無効なホスト設定：
+
iSCSI 、 FC 、またはマルチパス解決策が適切にセットアップされていません。

* ネットワークまたはスイッチの設定が無効です：
+
IP ネットワークに iSCSI トラフィック用の適切な転送ルールまたはフィルタが設定されていないか、 FC スイッチに推奨されるゾーニング設定が設定されていません。



上記の問題は、アルゴリズムやシーケンシャルな診断では非常に困難です。

What to do ： NetAppIt is recommended that you use SnapDrive for UNIX 、 you follow the Host Utilities Setup Guide （ for the specific operating system ）で推奨されている手順に従って、 LUN を手動で検出することを推奨します。

LUN を検出したら、 SnapDrive for UNIX のコマンドを使用します。



 a| 
「 0001-486 」
 a| 
12.
 a| 
管理
 a| 
LUN が使用中です削除できません注意： Volume Manager で制御されている LUN を ' 最初にボリューム・マネージャの制御から適切に削除せずに削除することは危険です
 a| 
SnapDrive for UNIX では、ボリュームグループに含まれている LUN は削除できません。

What to do ：次の手順を実行します。

. コマンド SnapDrive storage delete -dg <dgname> を使用して、ディスクグループを削除します。
. LUN を削除します。




 a| 
「 0001 」 ～ 「 494 」
 a| 
12.
 a| 
コマンドを実行します
 a| 
SnapDrive はまだ 1 つのホストボリュームが残っているため、 <mydg1> を削除できません。<mydg1> に関連付けられたすべてのファイルシステムとホストボリュームを削除するには、 -full-fullflag を使用します
 a| 
ディスクグループ上のすべてのホストボリュームの削除が明示的に要求されるまで、 SnapDrive for UNIX はディスクグループを削除できません。

対処方法：次のいずれかを実行します。

. コマンドで「 -full」 フラグを指定します。
. 次の手順を実行します。
+
.. ディスク・グループ上のホスト・ボリュームのリストを表示するには、 SnapDrive storage show -all コマンドを使用します。
.. SnapDrive for UNIX のコマンドで、これらのそれぞれを明示的に指定します。






 a| 
「 0001 」 ～ 「 541 」
 a| 
65
 a| 
コマンドを実行します
 a| 
「ファイラー上に LUN を作成するためのアクセス権限が不十分です。 <exocet>. 」というメッセージが表示されます
 a| 
SnapDrive for UNIX では、擬似アクセス制御メカニズムのために、ルート・ストレージ・システム（ Filer ）ボリューム上の「 dhostname.prbac 」または「 dgeneric.prbacfile 」を使用します。

対処方法：次のいずれかを実行します。

. 「 d-hostname.prbac 」または「 dgeneric 」を変更します。ストレージ・システムに prbac ファイルを追加して ' 次の必要な権限を追加します（ 1 つ以上）
+
.. なし
.. snap create
.. スナップ使用（ Snap Use ）
.. すべてスナップ（ Snap All ）
.. storage create delete
.. ストレージの使用
.. すべてのストレージ
.. すべてのアクセス
+
* 注： *

+
====
*** 「 d-hostname.prbac 」ファイルがない場合は、ストレージシステムで「 dgeneric.prbac 」ファイルを変更します。
*** 「 d-hostname.prbac 」と「 dgeneric.prbac 」ファイルの両方がある場合は、ストレージシステムの「 dhostname.prbac 」ファイルでのみ設定を変更します。


====


. 「 napdrive.conf 」ファイルで、「 all-access if-rbacunspecified 」コンフィギュレーション変数が「 on 」に設定されていることを確認します。




 a| 
「 0001 」 ～ 「 559 」
 a| 
該当なし
 a| 
管理
 a| 
スナップショットの取得中に I/O が検出されました。アプリケーションを休止してください。SnapDrive Admin を参照してください詳細については、ガイドを参照してください
 a| 
このエラーは、 Snapshot コピーを作成する際に、ファイル仕様に対して並行して入出力処理が実行され、「 napcreate-cg-timeout 」の値が urgent に設定されている場合に発生します。

What to do ：「 snapmirror-cg-timeout 」の値を relaxed に設定して、整合グループの値をタイムアウトにします。



 a| 
「 0001-570 」
 a| 
6.
 a| 
コマンドを実行します
 a| 
「ディスクグループ <dg1> は存在しないため、サイズを変更できません」
 a| 
このエラーは、ディスクグループがホストに存在しないためにコマンドが失敗した場合に発生します。

What to do ：次の手順を実行します。

. すべてのディスク・グループ名を取得するには、 SnapDrive storage show -all コマンドを使用します。
. 正しいディスクグループ名を指定してコマンドを実行します。




 a| 
「 0001-574 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
「 <VmAssistant>lvm 」では、ディスクグループ内の LUN のサイズ変更はサポートされていません
 a| 
このエラーは、このタスクの実行に使用するボリュームマネージャで LUN のサイズ変更がサポートされていない場合に発生します。

SnapDrive for UNIX の場合、 LUN がディスクグループに属しているときに、ボリュームマネージャの解決策が LUN のサイズ変更をサポートしている必要があります。

対処方法：使用しているボリュームマネージャが LUN のサイズ変更をサポートしているかどうかを確認します。



 a| 
「 0001-616 」
 a| 
6.
 a| 
コマンドを実行します
 a| 
'1 個のスナップショットがファイラーで見つかりません : exocet: /vol/vol1/vol:MySnapName>`
 a| 
SnapDrive for UNIX では、 Snapshot 処理を実行するために、コマンドラインで複数の Snapshot 名を指定することはできません。このエラーを解決するには、 Snapshot 名を 1 つ指定してコマンドを再実行します。

無効な Snapshot 名で Snapshot 処理が試行されたコマンドで、構文エラーが発生しています。このエラーを解決するには、次の手順を実行します。

. SnapDrive の Snapshot コピーのリストを表示するには、 lun snap list -ffiler <filer-volume -name> ` コマンドを使用します。
. コマンドを '*long_snap_name*' 引数を指定して実行します




 a| 
「 0001-640` 」
 a| 
1.
 a| 
コマンドを実行します
 a| 
ルート・ファイル・システム / は SnapDrive によって管理されていません
 a| 
このエラーは、ホスト上のルートファイルシステムが SnapDrive for UNIX でサポートされていない場合に発生します。これは SnapDrive for UNIX への無効な要求です。



 a| 
「 0001 」 ～ 「 684 」
 a| 
45
 a| 
管理
 a| 
`m マウントポイント <fs_spec> はマウントテーブルにすでに存在します
 a| 
対処方法：次のいずれかを実行します。

. 別のマウントポイントを指定して SnapDrive for UNIX コマンドを実行します。
. マウントポイントが使用されていないことを確認してから、任意のエディタを使用して手動で次のファイルからエントリを削除します。


Linux ： /etc/fstab



 a| 
0001-796 と 0001-767`
 a| 
3.
 a| 
コマンドを実行します
 a| 
0001-796 および 0001-767`
 a| 
SnapDrive for UNIX では、「 -nolvm 」オプションを指定した場合と同じコマンドで複数の LUN がサポートされません。

対処方法：次のいずれかを実行します。

. もう一度コマンドを使用して、「 -nolvm 」オプションを指定した LUN を 1 つだけ指定してください。
. --nolvm オプションを指定せずにコマンドを使用します。ホストにサポート対象のボリュームマネージャがある場合は、そのマネージャを使用します。




 a| 
「 2715 」
 a| 
該当なし
 a| 
該当なし
 a| 
'Volume restore Zephyr not available for the filer <filename> Please proceed with LUN restore' 」というメッセージが表示されます
 a| 
古いバージョンの Data ONTAP では、ボリュームリストア ZAPI を使用できません。コマンドを SFSR で再発行します。



 a| 
「 2278 」
 a| 
該当なし
 a| 
該当なし
 a| 
'snapname> のあとに作成されたスナップショットにはボリュームクローンがありません ... 失敗しました
 a| 
クローンをスプリットまたは削除します



 a| 
「 2280` 」
 a| 
該当なし
 a| 
該当なし
 a| 
LUN がマッピングされましたが ' アクティブではないか ' またはスナップショットに失敗しました
 a| 
ホストエンティティのマッピング解除 / ストレージ切断を行います



 a| 
「 2282 」
 a| 
該当なし
 a| 
該当なし
 a| 
SnapMirror 関係が存在しません ... 失敗しました
 a| 
. 関係を削除するか、をクリックします
. Operations Manager を使用した SnapDrive for UNIX RBAC が構成されている場合は、 Operations Manager 管理者に「 D 」の Snapshot.DisruptBaseline 」機能をユーザに付与するよう依頼します。




 a| 
「 2286 」と入力します
 a| 
該当なし
 a| 
該当なし
 a| 
'LUNs not owned by <fsname> are application consistent in snapshotted volumes... （ <fsname> が所有していない LUN は、スナップショットボリューム内で 失敗しました。スナップショット LUN は <fsname> によって所有されていません。これは、アプリケーションに整合性がない可能性があります
 a| 
チェック結果に示された LUN が使用中でないことを確認してください。そのあとにのみ、「 -force 」オプションを使用します。



 a| 
2289`
 a| 
該当なし
 a| 
該当なし
 a| 
'No new LUNs created after snapshot <snapname> … 失敗しました
 a| 
チェック結果に示された LUN が使用中でないことを確認してください。そのあとにのみ、「 -force 」オプションを使用します。



 a| 
「 2290` 」
 a| 
該当なし
 a| 
該当なし
 a| 
「一貫性のない新しい LUN チェックを実行できませんでした。スナップショットバージョンは SDU 4.0` より前です
 a| 
これは '-vbsr と一緒に使用した場合に 'UNIX スナップショット用の SnapDrive 3.0 で発生します新しく作成された LUN がもう使用されないことを手動で確認してから '-force オプションを続行してください



 a| 
2292`
 a| 
該当なし
 a| 
該当なし
 a| 
' 新しいスナップショットは存在しません ... 失敗しました。作成されたスナップショットは失われます
 a| 
チェック結果に示されたスナップショットが使用されなくなったことを確認します。その場合は、「 -force 」オプションに進みます。



 a| 
2297`
 a| 
該当なし
 a| 
該当なし
 a| 
通常のファイルと LUN の両方が存在します ... 失敗しました
 a| 
チェック結果に示されたファイルと LUN が使用されなくなっていることを確認します。その場合は、「 -force 」オプションに進みます。



 a| 
「 2302 」
 a| 
該当なし
 a| 
該当なし
 a| 
NFS エクスポート・リストに外部ホストがありません ... 失敗しました
 a| 
ストレージ管理者に連絡してエクスポートリストから外部ホストを削除するか、外部ホストが NFS 経由でボリュームを使用していないことを確認します。



 a| 
「 9000-305`
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
' エンティティ /mnt/my_fs のタイプを検出できませんでしたエンティティーのタイプがわかっている場合は ' 特定のオプション（ -lun '-dg '-fs または -lvol ）を指定します
 a| 
エンティティがホストにすでに存在する場合は確認してください。エンティティのタイプがわかっている場合は、 file-spec タイプが提供されます。



 a| 
「 9000-303`
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「同じ名前の複数のエンティティ - /mnt/my_fs がこのホストに存在します。指定したエンティティに固有のオプション（ -lun 、 -dg 、 -fs 、 -lvol ）を指定します
 a| 
ユーザには同じ名前のエンティティが複数あります。この場合、ユーザは file-spec タイプを明示的に指定する必要があります。



 a| 
「 9000-304 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「 /mnt/my_fs 」は、タイプファイルシステムのキーワードとして検出されますが、このコマンドではサポートされていません
 a| 
このコマンドでは ' 自動検出されたファイル・スペシフィケーションに対する操作はサポートされていません作業のヘルプを参照して確認します。



 a| 
「 9000-301 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「自動防御における内部エラー」
 a| 
自動検出エンジンエラー。トレースログとデーモンログを指定して、詳細な分析を行います。



 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
'napdrive.dc ツールは RHEL 5Ux 環境でデータを圧縮できません
 a| 
デフォルトでは、圧縮ユーティリティはインストールされません。圧縮ユーティリティ ncompress をインストールする必要がありますたとえば 'ncompress-4.2.4-47.i386.rpm' のようにします

圧縮ユーティリティをインストールするには、次のコマンドを入力します。「 rpm -ivh ncompress-4.2.4-47.i386.rpm



 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「無効なファイル仕様」
 a| 
このエラーは、指定したホストエンティティが存在しないか、アクセスできない場合に発生します。



 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
ジョブ ID が無効です
 a| 
このメッセージは、指定したジョブ ID が無効なジョブであるか、ジョブの結果がすでに照会された場合に、クローンスプリットのステータス、結果、または停止処理について表示されます。有効なジョブ ID または使用可能なジョブ ID を指定して、この処理を再試行する必要があります。



 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「計画はすでに進行中です
 a| 
このメッセージは、次の場合に表示されます。

* 指定したボリュームクローンまたは LUN クローンについて、クローンスプリットをすでに実行中です。
* クローンスプリットは完了しましたが、ジョブは削除されていません。




 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
' 有効なボリュームではありません - クローンまたは LUN- クローン
 a| 
指定したファイル仕様または LUN パス名は、有効なボリューム・クローンまたは LUN クローンではありません。



 a| 
該当なし
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「ボリュームを分割するスペースがありません
 a| 
このエラーメッセージは、必要なストレージスペースを分割できないことが原因で表示されます。ボリュームクローンをスプリットするための十分なスペースをアグリゲート内に確保します。



 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
「 filer-data: junction-path 」情報は使用できません。 LUN はオフラインになっている可能性があります
 a| 
このエラーは '/etc/fstab ファイルが正しく構成されていないときに発生する可能性がありますこの場合、マウントパスは NFS ですが、 SnapDrive for UNIX では LUN とみなされていました。

対処方法：ストレージシステム名とジャンクションパスの間にを追加します。



 a| 
0003-013`
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
仮想インターフェイス・サーバで接続エラーが発生しました仮想インターフェイスサーバが稼働しているかどうかを確認してください
 a| 
このエラーは、 ESX サーバのライセンスが期限切れになり、 VSC サービスが実行されていない場合に発生することがあります。

What to Do ： ESX Server ライセンスをインストールし、 VSC サービスを再起動します。



 a| 
「 0002 」 ～ 「 137 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
'10.231.72.21 の場合は 'fstype と mntOpts を取得できませんスナップショット 10.231.72.21 の場合は /vol/ips_vol: /vol/ips_vol3: T5120-206-66_nfssnap.` から vol/ips_vol3 を取得できません
 a| 
What to do ：次のいずれかを実行します

. データパス・インターフェイスの IP アドレス、またはホスト名として特定の IP アドレスを「 /etc/hosts 」ファイルに追加します。
. DNS でデータパス・インターフェイスまたはホスト名 IP アドレスのエントリを作成します。
. SVM 管理をサポートするように SVM のデータ LIF を設定する（ firewall-policy = mgmt を使用）
+
*net int modify -- vserver Vserver_name lif_name -firewall-policy mgmt *

. ホストの管理 IP アドレスを SVM のエクスポートルールに追加します。




 a| 
「 13003 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
「権限不足：ユーザーにはこのリソースへの読み取りアクセス権がありません。
 a| 
この問題は、 SnapDrive for UNIX 5.2.2 で表示されています。SnapDrive for UNIX 5.2.2 より前のバージョンでは、 SnapDrive for UNIX で設定した vsadmin ユーザには「 vsadmin-volume 」ロールが必要です。UNIX 5.2.2 の SnapDrive では、 vsadmin ユーザには昇格されたアクセスロールが必要ですが、 snapmirror get-iter zapi が失敗します。

操作： vsadmin-volume ではなく vsadmin ロールを作成し、 vsadmin ユーザに割り当てます。



 a| 
「 0001 」 ～ 「 016 」
 a| 
該当なし
 a| 
コマンドを実行します
 a| 
ストレージ・システム上のロック・ファイルを取得できませんでした
 a| 
ボリュームに十分なスペースがないために Snapshot の作成が失敗する。または ' ストレージ・システムに「 .snapDrive_lock 」ファイルが存在するためです

対処方法：次のいずれかを実行します。

. ストレージ・システム上のファイル「 /vol/<volname>/<snaps_lock' 」を削除し、 snap create 処理を再試行します。ファイルを削除するには、ストレージ・システムにログインし、 advanced 権限モードに切り替えて、ストレージ・システム・プロンプトで「 rm /vol/<volname>/<volname>/.snapDrive_lock` コマンドを実行します。
. Snapshot を作成する前に、ボリュームに十分な空きスペースがあることを確認してください。




 a| 
「 0003-003 」
 a| 
該当なし
 a| 
管理
 a| 
「ストレージシステムの LUN < コントローラ名 > をゲスト OS にエクスポートできませんでした。理由： flow-11019: MapStorage での障害 : interface .` で構成されたストレージ・システムがありません
 a| 
このエラーは、 ESX サーバでストレージコントローラが設定されていない場合に発生します。

操作： ESX サーバにストレージコントローラとクレデンシャルを追加します。



 a| 
「 0001 」 ～ 「 493 」
 a| 
該当なし
 a| 
管理
 a| 
マウントポイントの作成エラー : mkdir からの予期しないエラー : mkdir : ディレクトリを作成できません : permission denied マウントポイントが automount パスの下にあるかどうかを確認してください
 a| 
デスティネーションファイル仕様に自動マウントパスが指定されている場合、クローン処理が失敗します。

対処方法：デスティネーションファイル仕様 / マウントポイントが自動マウントパスの下にないことを確認します。



 a| 
「 0009-049` 」
 a| 
該当なし
 a| 
管理
 a| 
' ストレージシステム上の Snapshot からのリストアに失敗しました :Vserver 上のボリュームの Snapshot コピーからファイルをリストアできませんでした
 a| 
このエラーは、ボリュームがフルの状態か、ボリュームが自動削除のしきい値を超えた場合に発生します。

対処方法：ボリュームサイズを拡張し、ボリュームのしきい値が自動削除の値よりも小さくなっていないことを確認します。



 a| 
「 0001 」 ～ 「 682 」
 a| 
該当なし
 a| 
管理
 a| 
' 新しい LUN のホスト準備に失敗しました : この機能はサポートされていません
 a| 
このエラーは、新しい LUN ID の作成に失敗した場合に発生します。

What to do ：を使用して作成する LUN の数を増やします

'*lun SnapDrive config prepare LUNs_-count count_value_*

コマンドを実行します



 a| 
「 0001 」 ～ 「 060 」
 a| 
該当なし
 a| 
管理
 a| 
「ディスクグループ情報の取得に失敗しました。 Volume Manager linuxlvm が vgdisplay コマンドを返しました
 a| 
このエラーは、 SnapDrive for UNIX 4.1.1 以降のバージョンが RHEL 5 以降のバージョンで使用されている場合に発生します。

対処方法： SnapDrive バージョンをアップグレードしてから再試行してください。 SnapDrive for UNIX 4.1.1 以降のバージョンではサポートが提供されていないためです。 RHEL5 以降ではサポート対象外です。



 a| 
「 0009-045` 」
 a| 
該当なし
 a| 
管理
 a| 
'Failed to create snapshot on storage system: スナップショットによってバックアップされたクローンのため ' スナップショット操作は許可されませんしばらくしてからもう一度お試しください
 a| 
このエラーは、 Single-File Snap Restore （ SFSR ）処理の実行中に、そのあとで Snapshot をただちに作成するときに発生します。

What to do ：しばらくしてから Snapshot の作成処理を再試行してください。



 a| 
「 0001 」 ～ 「 304 」
 a| 
該当なし
 a| 
管理
 a| 
ディスク / ボリュームグループの作成中にエラーが発生しましたボリュームマネージャは次のように失敗しました : metainit : No such file or directory
 a| 
このエラーは 'Sun Cluster 環境で SnapDrive storage create dg 'hostvol および fs solaris を実行しているときに発生します

操作 : Sun Cluster ソフトウェアをアンインストールしてから ' 操作を再試行します



 a| 
「 0001 」 ～ 「 122 」
 a| 
該当なし
 a| 
管理
 a| 
'Failed to get snapshot list on filer the specified volume <volname> does not exist.`
 a| 
このエラーは、 SnapDrive for UNIX が、ダミーのエクスポートされたボリュームパスではなく、ボリュームのエクスポートされたアクティブファイルシステムパス（実際のパス）を使用して Snapshot を作成しようとした場合に発生します。

What to do ：エクスポートされたアクティブファイルシステムパスを持つボリュームを使用します。



 a| 
「 0001 」 ～ 「 476 」
 a| 
該当なし
 a| 
管理
 a| 
' デバイスを検出できませんマルチパスを使用している場合は、マルチパス構成にエラーがある可能性があります。設定を確認してから、もう一度やり直してください
 a| 
このエラーが発生する理由はいくつかあります。

チェックする条件は次のとおりです。ストレージを作成する前に、ゾーニングが適切であることを確認してください。

「 napdrive.conf 」ファイルの転送プロトコルとマルチパスタイプを調べ、適切な値が設定されていることを確認します。

マルチパスデーモンのステータスを確認します。 multipathing-type が nativemio start multipathd に設定されている場合は、 snapdrived デーモンを再起動します。



 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
lv. が使用できないため 'FS は再起動後にマウントできません
 a| 
これは、リブート後に LV を使用できない場合に発生します。そのため、ファイルシステムはマウントされていません。

対処方法 : 再起動後、 vgchange を実行して LV を起動し、ファイルシステムをマウントします。



 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
'SDU デーモンへの tatus 呼び出しが失敗しました
 a| 
このエラーが発生する理由はいくつかあります。このエラーは、処理が完了する前に、特定の処理に関連する SnapDrive for UNIX ジョブが突然失敗した（子デーモンが終了した）ことを示します。

ストレージの作成または削除が「 Status call to SnapDrive for UNIX daemon failed 」というメッセージで失敗した場合は、 ONTAP によるボリューム情報の取得に失敗した可能性があります。volume-get-iter zapi が失敗することがあります。しばらくしてから SnapDrive 処理を再試行してください。

「 multipath.conf 」の値が不適切なため、パーティションやその他のオペレーティングシステムコマンドの作成中に「 kpartx-l 」を実行すると、 SnapDrive for UNIX 操作が失敗することがあります。正しい値が設定されており、「 multipath.conf 」ファイルに重複するキーワードが存在しないことを確認してください。

SFSR の実行中、 SnapDrive for UNIX は一時的な Snapshot を作成します。 Snapshot の最大数に達した場合、この Snapshot は失敗する可能性があります。古い Snapshot コピーを削除して、リストア処理を再試行します。



 a| 
該当なし
 a| 
該当なし
 a| 
該当なし
 a| 
「使用中の AP 。フラッシュできません。
 a| 
このエラーは、ストレージの削除処理または切断処理中にマルチパスデバイスのフラッシュを試行したときに、古くなったデバイスが残っている場合に発生します。

What to do ：コマンドを実行して、古いデバイスがないかどうかを確認します

「 * マルチパス * 」

`--l egre-ifail_` と '`_flush_on_last_del_` が「 multipath.conf 」ファイルで 'yes' に設定されていることを確認します。

|===
* 関連情報 *

https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["『 Linux Unified Host Utilities 7.1 Installation Guide 』"]
