---
permalink: linux-administration/task_setting_values_in_the_snapdrive_conf_file.html 
sidebar: sidebar 
keywords: snap, snapdrive, conf, value, name 
summary: snapdrive.conf ファイルの値を変更したり、新しい名前と値のペアを追加したりできます。 
---
= snapdrive.conf ファイルの値の設定
:icons: font
:imagesdir: ../media/


[role="lead"]
「 napdrive.conf 」ファイルの値を変更したり、新しい名前と値のペアを追加したりできます。

root ユーザとしてログインする必要があります。

.手順
. 「 napdrive.conf 」ファイルをバックアップします。
. テキストエディタで 'napdrive.conf ファイルを開きます
. 名前と値のペアを追加するには、次の形式を使用します。
+
`*config-option-name = value value # オプションのコメント *``

+
`_config -option-name_` は、構成する変数の名前です。例えば、 audit-log-file です。`_value_` は ' このオプションに割り当てる値です

+
名前と値のペアにコメントを含める場合は、コメントの前に番号記号（ # ）を付けます。

+
1 行に入力できる名前と値のペアは 1 組だけです。

+
名前または値が文字列を使用する場合は、文字列を単一（ '' ）または二重（ " ）引用符で囲みます。引用符は、名前と値のペア全体またはその前後のいずれかに配置できます。次の例は、名前と値のペアで引用符とコメントを使用する方法を示しています。

+
`*`"config-option-1= 空白文字列 "# ペアを二重引用符で囲む *`

+
*config-option-bo="string with white space" # 値 *` を二重引用符で囲んで指定します

+
*config-option-2B= 「空白を含む」 # 値 *` を囲む一重引用符

. 名前と値のペアを変更するには、現在の値を新しい値に置き換えます。
+
デフォルト値がファイルに記録されていることを確認するには、次の手順に従います。

+
.. 変更する行に記号（ # ）を追加します。
.. 行をコピーします。
.. 番号記号 (#) を削除して、コピーしたテキストをアクティブにします。
.. 値を修正します。


+
空の値を指定する場合（監査ログファイルを無効にする場合など）は、二重引用符（ "" ）を 1 組入力します。

. 変更を行ったらファイルを保存します。
+
SnapDrive for UNIX では、起動するたびにこのファイルが自動的にチェックされます。変更内容は、次回の起動時に有効になります。

. 「管理された restart 」コマンドを使用して、 SnapDrive for UNIX デーモンを再起動します。
+
「 napdrive.conf 」ファイルの変更を有効にするには、デーモンを再起動する必要があります。


