---
permalink: linux-administration/task_considerations_for_provisioning_rdm_luns.html 
sidebar: sidebar 
keywords: snap, snapdrive, rdm, lun, provisioning 
summary: SnapDrive for UNIX では、 RDM LUN のプロビジョニングに関するいくつかの考慮事項があります。 
---
= RDM LUN のプロビジョニングに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX では、 RDM LUN のプロビジョニングに関するいくつかの考慮事項があります。

* ゲスト OS の「 napdrive.conf 」ファイルで、構成変数「 default -transport 」が「 fcp 」に設定されていることを確認します。
* SnapDrive for UNIX から NetApp Virtual Storage Console for VMware vSphere にアクセスするように設定します。
* RDM LUN サポートの構成変数が「 snapdrive.conf 」ファイルで使用されていることを確認します。'contact-viadmin-port 、 use-https-to-viadmin 、 vif-password -file' および 'virtualization-operation-timeoutsecs=600' などの変数は、 RDM LUN のサポートに使用されます。


* 関連情報 *

xref:concept_limitations_of_rdm_luns_managed_by_snapdrive.adoc[SnapDrive で管理される RDM LUN の制限事項]

xref:concept_storage_provisioning_for_rdm_luns.adoc[SnapDrive for UNIX での VMware VMotion のサポート]

xref:task_configuring_virtual_storage_console_in_snapdrive_for_unix.adoc[Virtual Storage Console for SnapDrive for UNIX を設定しています]

xref:concept_configuration_options_and_their_default_values.adoc[構成オプションとそのデフォルト値]
