---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: 'SnapDrive for UNIX でマルチパスを使用するには、 HBA のインストールと起動を含む手順を完了する必要があります。NetApp 以外のマルチパス解決策を使用している場合は "HBA ベンダーの Web サイトからソフトウェアとアプリケーションのパッケージをダウンロードする必要があります' 
---
= マルチパスの有効化
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX でマルチパスを使用するには、 HBA のインストールと起動を含む手順を完了する必要があります。ネットアップ以外のマルチパス解決策を使用している場合は、 HBA ベンダーの Web サイトからソフトウェアとアプリケーションのパッケージをダウンロードする必要があります。

システムで FC および iSCSI の最新バージョンのシステムコンポーネントが実行されている必要があります。

http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

.手順
. 適切な Host Utilities ソフトウェアをインストールする前に、サポートされている HBA をインストールしてください。
+

NOTE: SnapDrive for UNIX はマルチベンダー HBA をサポートします。

. HBA サービスを開始します。
+
HBA サービスが実行されていない場合は、 SnapDrive for UNIX コマンド（ SnapDrive storage create や SnapDrive config prepare LUN' など）を実行すると、次のエラー・メッセージが表示されます。

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
必要な数のパスが動作していることを確認する必要があります。パスを確認するには 'Host Utilities ソフトウェアに含まれている 'anlun' ユーティリティを使用しますたとえば、 FC マルチパス構成では、「 lun fcp show adapter -v 」コマンドを使用できます。

+
次の例では、動作可能な（ポート状態）ホストに 2 つの HBA ポート（ fcd0 および fcd1 ）が接続されています。HBA または iSCSI イニシエータは 1 つだけ使用でき、ターゲット LUN へのパスを複数設定することでマルチパスを設定する必要があります。

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
ホストでマルチパスが有効になっている場合は、同じ LUN から複数のパスが認識されます。「 lun lun lun show all 」コマンドを使用してパスを確認できます。次の例では、同じ LUN への複数のパス（「 fish:/vol/vol1/LUN」 ）を検索できます。

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. SnapDrive for UNIX または Host Utilities で他社製マルチパス解決策がサポートされている場合は、 HBA ベンダーの Web サイトから HBA ドライバのソフトウェアパッケージとアプリケーションパッケージをダウンロードします。 * QLogic* ： QLogic HBA の場合は、に進みます http://support.qlogic.com/[]。OEM モデルから、ネットアップを選択します。サポートマトリックスに記載されているバージョンのドライバを探してダウンロードします。* Emulex ： * Emulex HBA の場合は、に進みます。Downloads （ダウンロード）で、 NetApp （ネットアップ）を選択サポートマトリックスに記載されているバージョンのドライバを探してダウンロードします。同じ場所から Emulex アプリケーションパッケージもダウンロードします。
+
FC 接続で QLogic アダプタを使用している場合は 'QLogic の Web サイトから QLogic 再スキャンスクリプトをダウンロードして '/root' パスにコピーします ( 例 : ルート / ダイナミック LUN-rescan.sh`)ユーザの確認を求める QLogic 再スキャンスクリプトが表示されます。 SnapDrive for UNIX はこの確認段階で無期限に停止する可能性があります。この確認を回避するには ' スクリプト内で変数 '_QL_DISABLE_WARNING_' を 1' に設定します

+
以前のバージョンの SnapDrive for UNIX では ' ベンダー固有の SCSI 再スキャン・スクリプトを使用して FC 経由で LUN をスキャンし ' ベンダー固有のスクリプトをルート / ダイナミック LUN-rescan.sh にコピーしていましたこれは RHEL 5U3 まで使用可能でした。

+
RHEL 5U4/SLES 10SP2 以降のバージョンでは、現在、 rescan スクリプトは /usr/bin' ディレクトリにあります。ディレクトリに再スキャン・スクリプトがない場合 '`G3_utils` パッケージとともに存在します

+

NOTE: Red Hat Enterprise Linux （ RHEL ）および Oracle Enterprise Linux （ OEL ）バージョンでは、「 g3_utils 」および「 g3_utils-libs 」ライブラリが利用可能であることを確認する必要があります。ただし、「 G3_utils 」ライブラリは、「 CSCI utility.rpm 」パッケージの SUSE Linux Enterprise Server （ SLES ）バージョンで使用できます。

. FC 構成で、スイッチのゾーニング設定を使用して、ホスト HBA ポートとターゲットポートをゾーニングします。
. 適切な FC スイッチを設置してセットアップします。
. SnapDrive で UNIX スタックの要件を確認します。
. SnapDrive for UNIX をインストールまたはアップグレードします。
. SnapDrive for UNIX のインストールを確認します。
. 「 napdrive.conf 」ファイルパスを探します。
. 「 napdrive.conf 」ファイルで次の設定変数を設定します。
+
** `_multipathing-type_`
** `_default-transport_`
** 「 _fstype_` 」
** `_vmtype_`
+
どのホストでも、マルチパスタイプ、転送タイプ、ファイルシステム、ボリュームマネージャのタイプは相互に依存します。次の表に、使用可能なすべての組み合わせを示します。

+
|===
| ホストプラットフォーム | デフォルトの転送タイプ | マルチパスタイプ | FSstype （英語） | vmtype を指定します 


 a| 
Linux の場合
 a| 
iSCSI
 a| 
nativempio
 a| 
ext4 または ext3 のいずれかです
 a| 
LVM



 a| 
iSCSI
 a| 
なし
 a| 
ext4 または ext3 のいずれかです
 a| 
LVM



 a| 
FCP
 a| 
なし
 a| 
ext4 または ext3 のいずれかです
 a| 
LVM



 a| 
FCP
 a| 
nativempio
 a| 
ext4 または ext3 のいずれかです
 a| 
LVM

|===
+
上記の表は '_multipathing-type_`'_default-transport_'`_fstype_`'_vmtype_` 構成変数のサポートされる値を示しています

+

NOTE: トランスポート・プロトコルが iSCSI で ' マルチパス・タイプが none に設定されている場合は ' マルチパス・デーモンを停止して 'UNIX コマンドの SnapDrive を実行する必要があります



. 「 napdrive.conf 」ファイルを保存します。
+
SnapDrive for UNIX では、起動するたびにこのファイルが自動的にチェックされます。変更を有効にするには、 SnapDrive for UNIX デーモンを再起動する必要があります。



* 関連情報 *

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[マルチパスタイプの移行後、 Linux で SnapRestore 処理と Snapconnect 処理は機能しません]

http://mysupport.netapp.com["ネットアップサポート"]

https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["『 Linux Unified Host Utilities 7.1 Installation Guide 』"]
