---
permalink: linux-administration/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file, name 
summary: ログファイルを有効にする場合は、有効にするログファイルの名前と値のペアの値としてファイル名を指定します。ファイルを無効にする場合は、ログファイル名パラメータの値を入力しないでください。 
---
= ログファイルを有効または無効にします
:icons: font
:imagesdir: ../media/


[role="lead"]
ログファイルを有効にする場合は、有効にするログファイルの名前と値のペアの値としてファイル名を指定します。ファイルを無効にする場合は、ログファイル名パラメータの値を入力しないでください。

root ユーザとしてログインしておく必要があります。

.手順
. テキストエディタで 'napdrive.conf ファイルを開きます
. ログファイルを有効または無効にするオプションを選択します。
+
|===
| 状況 | 作業 


 a| 
* ログファイルを有効にします *
 a| 
 Specify a file name as the value in the name-value pair of the log file you want to enable. SnapDrive for UNIX only writes log files if it has the name of a file to write to. The default names for the log files are as follows:
** 監査ログ : 'daudit.log
** リカバリログ : 'd-recovery.log
** トレースログ : 'd-ctrace-log



NOTE: これらのファイルへのパスは、ホストオペレーティングシステムによって異なる場合があります。



 a| 
* ログファイルを無効にします *
 a| 
 Do not enter a value for the log file name parameter. If you do not supply a value, there is no file name to which SnapDrive for UNIX can write the log information.
* 例 * この例は、監査ログファイルを無効にします。'audit-log-file=""

|===
. すべての変更を行ったら 'napdrive.conf ファイルを保存します
+
SnapDrive for UNIX では、起動するたびにこのファイルが自動的にチェックされます。変更を有効にするには、 SnapDrive for UNIX デーモンを再起動する必要があります。


