---
permalink: aix/concept_automatic_detection_of_host_entities.html 
sidebar: sidebar 
keywords: snap, snapdrive, automatic, detection, host, entities 
summary: SnapDrive for UNIX では、一部のコマンドについて、ホストエンティティの設定が自動的に検出されます。いくつかの snap storage コマンドで必要になるのは、ホストエンティティの名前だけです。その場合、ホストエンティティのタイプを指定する必要はありません。 
---
= ホストエンティティの自動検出
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX では、一部のコマンドについて、ホストエンティティの設定が自動的に検出されます。いくつかの snap storage コマンドは ' ホストエンティティの名前だけを必要としますその場合、ホストエンティティのタイプを指定する必要はありません。

自動検出を有効にするコマンドは次のとおりです。

* 「 storage delete 」をクリックします
* 「ストレージのサイズ変更」
* 'snap create ’
* 'snap restore ( スナップ復元
* 'snap connect`
* 「スナップリスト」


ホストエンティティが存在する場合は、 SnapDrive for UNIX によってホストエンティティのタイプが自動的に検出されます。この場合、ホストエンティティの名前だけを指定する必要があり、タイプを指定する必要はありません。SnapDrive snap コマンドと一部の「 storage 」コマンドでは、ホストエンティティの名前だけを指定する必要があります。タイプを指定する必要はありません。

SnapDrive 4.1 以降では、コマンドの自動検出に時間がかかります。これは、すべてのストレージリソースの詳細が収集されるためです。応答時間を短縮するには、 SnapDrive for UNIX コマンドを使用してファイル仕様を指定します。

ストレージ削除操作の自動検出を有効にするには、 SnapDrive storage delete コマンドを実行します。

* 例 1 ： *

[listing]
----
snapdrive storage delete host_dg my_fs -full
----
この例では 'host_dg と `m_f' が自動的に検出されます

* 例 2 ： *

[listing]
----
snapdrive storage delete mydg -fs myfs -full
----
この例では、「 dg 」ディスクグループが自動的に検出されます。

SnapDrive storage resize コマンドを実行すると、ストレージ・サイズ変更操作の自動検出を有効にできます。

* 例 * ：

[listing]
----
[root@lnx197-132 ~]# snapdrive storage resize mydg23 -addlun -growby 10m
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
        discovering filer LUNs in disk group mydg23...done
        LUN bart:/vol/voldm/mydg23-1_SdLun ... created

        mapping new lun(s) ... done
        discovering new lun(s) ... done.
        initializing LUN(s) and adding to disk group mydg23...done
Disk group mydg23 has been resized
----
SnapDrive snap create コマンドを実行すると、スナップ作成操作の自動検出を有効にできます。

* 例 * ：

[listing]
----
root@lnx197-132 ~]# snapdrive snap create mydg22 mydg23 /mnt/mnt12 -snapname new_snap
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec '/mnt/mnt12 ' in progress ... detected as file system

Starting snap create /dev/mapper/mydg22, /dev/mapper/mydg23, /mnt/mnt12
  WARNING:  DO NOT CONTROL-C!
            If snap create is interrupted, incomplete snapdrive
                 generated data may remain on the filer volume(s)
                 which may interfere with other snap operations.
Successfully created snapshot new_snap on bart:/vol/voldm

        snapshot new_snap contains:
        disk group mydg22
        disk group mydg23
        disk group dg121 containing host volumes
                lv121 (filesystem: /mnt/mnt12)
----
SnapDrive snap connect コマンドを実行することで、スナップ接続操作の自動検出をイネーブルにできます。

* 例 * ：

[listing]
----
[root@lnx197-132 ~]# snapdrive snap connect mydg22 xxx mydg23 yyy -snapname bart:/vol/voldm:snap_1
Auto detecting the type of filespec 'mydg22' in progress ... detected as disk group
Auto detecting the type of filespec 'xxx' in progress ...
        xxx does not exist - Taking xxx as a destination to fspec mydg22Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group
Auto detecting the type of filespec 'yyy' in progress ...
        yyy does not exist - Taking yyy as a destination to fspec mydg23
 connecting mydg22:
        LUN copy mydg22_SdLun_0 ... created
                 (original: bart:/vol/voldm/mydg22_SdLun)

        mapping new lun(s) ... done

 connecting mydg23:
        LUN copy mydg23_SdLun_1 ... created
                 (original: bart:/vol/voldm/mydg23_SdLun)

        mapping new lun(s) ... done
        discovering new lun(s) ... done
        Importing xxx, yyy
Successfully connected to snapshot bart:/vol/voldm:snap_1
        disk group xxx
        disk group yyy
----
snap SnapDrive restore コマンドを実行すると、スナップ・リストア処理の自動検出を有効にできます。

* 例 * ：

[listing]
----
snapdrive snap restore bart:/vol/voldm/lun44 /mnt/fs3 fs5_SdDg/fs5_SdHv fs4_SdDg -snapname bart:/vol/voldm:toi_snap

        Auto detection of file_spec(s) in progress ...
               - 'bart:/vol/voldm/lun44' detected as LUN.
               - '/mnt/fs3' detected as file system.
               - 'fs5_SdDg/fs5_SdHv' detected as logical volume.
               - 'fs4_SdDg' detected as disk group.
        Starting to restore /dev/mapper/fs4_SdDg, /mnt/fs3, /dev/mapper/fs5_SdDg-fs5_SdHv, bart:/vol/voldm/lun44
         WARNING:  This can take several minutes.
           DO NOT CONTROL-C!
           If snap restore is interrupted, the filespecs
           being restored may have inconsistent or corrupted
           data.
       For detailed progress information, see the log file /var/log/sd-recovery.log
           Importing fs4_SdDg, fs3_SdDg, fs5_SdDg
           Successfully restored snapshot toi_snap on bart:/vol/voldm
       disk group fs4_SdDg containing host volumes
               fs4_SdHv (filesystem: /mnt/fs4)
       disk group fs3_SdDg containing host volumes
               fs3_SdHv (filesystem: /mnt/fs3)
       disk group fs5_SdDg containing host volumes
               fs5_SdHv (filesystem: /mnt/fs5)
       raw LUN: bart:/vol/voldm/lun44
----
SnapDrive では、ファイル仕様に誤りがある場合に snap connect 処理および snap restore 処理を自動的に検出することはできません。

SnapDrive snap list コマンドを実行すると、スナップ・リスト処理の自動検出を有効にできます。

* 例 * ：

[listing]
----
root@lnx197-132 ~]# snapdrive snap list -snapname bart:/vol/voldm:snap_1

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
[root@lnx197-132 ~]# snapdrive snap list mydg23
Auto detecting the type of filespec 'mydg23' in progress ... detected as disk group

snap name                            host                   date         snapped
--------------------------------------------------------------------------------
bart:/vol/voldm:snap_1           lnx197-132.xyz.com Apr  9 06:04 mydg22 mydg23 dg121
bart:/vol/voldm:all                  lnx197-132.xyz.com Apr  9 00:16 mydg22 mydg23 fs1_SdDg
bart:/vol/voldm:you                  lnx197-132.xyz.com Apr  8 21:03 mydg22 mydg23
bart:/vol/voldm:snap_2                  lnx197-132.xyz.com Apr  8 18:05 mydg22 mydg23
----