---
permalink: aix/concept_default_values_for_the_recovery_logs.html 
sidebar: sidebar 
keywords: snap, snapdrive, default, value, recovery, log 
summary: SnapDrive for UNIX で保存されるリカバリログファイルの名前および古いリカバリログファイルの最大数を変更できます。 
---
= リカバリ・ログのデフォルト値
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX で保存されるリカバリログファイルの名前および古いリカバリログファイルの最大数を変更できます。

'napdrive.conf' ファイルを使用すると ' リカバリ・ログに次の値を設定できます

* 「 recrecover.log 」など、リカバリログが格納されているファイルの名前。
* SnapDrive for UNIX で保存される、古いリカバリファイルの最大数。デフォルトは 20. です。SnapDrive for UNIX は、プロセスの問題がすぐに特定されない場合に、この数のリカバリログを保持します。SnapDrive for UNIX は、処理が完了するたびに新しいリカバリ・ログ・ファイルを開始します。次に、名前に任意の番号を追加して、以前の名前を変更します。例えば、 'recti.log.0'`recti.log.1' などです。



NOTE: リカバリログファイルのサイズは、実行される処理によって異なります。各リカバリログには、 1 つの処理に関する情報が含まれています。その処理が完了すると、前のファイルのサイズに関係なく、 SnapDrive for UNIX は新しいリカバリログを開始します。そのため、リカバリログファイルには最大サイズはありません。

次に、 SnapDrive for UNIX が、処理停止の前に 2 つの Snapshot コピーをリストアしたことを示すリカバリ・ログの例を示します。このリカバリログファイルをテクニカルサポートに送信して、残りの Snapshot コピーをリストアする際の支援を受けることができます。

[listing]
----
6719: BEGIN 15:52:21 03/09/04 snapdrive snap restore -dg jssdg -
snapname natasha:/vol/vol1:abort_snap_restore
6719: BEGIN 15:52:27 03/09/04 create rollback snapshot:
natasha:/vol/vol1:abort_snap_restore.RESTORE_ROLLBACK_03092004_155
225
6719: END 15:52:29 03/09/04 create rollback snapshot:
natasha:/vol/vol1:abort_snap_restore.RESTORE_ROLLBACK_03092004_155
225 successful
6719: BEGIN 15:52:29 03/09/04 deactivate disk group: jssdg
6719: BEGIN 15:52:29 03/09/04 stop host volume:
/dev/vx/dsk/jssdg/jvol_1
6719: END 15:52:30 03/09/04 stop host volume:
/dev/vx/dsk/jssdg/jvol_1 successful
6719: BEGIN 15:52:30 03/09/04 unmount file system: /mnt/demo_fs
6719: END 15:52:30 03/09/04 unmount file system: /mnt/demo_fs
successful
6719: BEGIN 15:52:30 03/09/04 stop host volume:
/dev/vx/dsk/jssdg/jvol_2
6719: END 15:52:30 03/09/04 stop host volume:
/dev/vx/dsk/jssdg/jvol_2 successful
6719: BEGIN 15:52:30 03/09/04 deport disk group: jssdg
6719: END 15:52:30 03/09/04 deport disk group: jssdg successful
6719: END 15:52:30 03/09/04 deactivate disk group: jssdg
successful
6719: BEGIN 15:52:31 03/09/04 SFSR of LUN: /vol/vol1/lun1 from
snapshot: abort_snap_restore
6719: END 15:52:31 03/09/04 SFSR of LUN: /vol/vol1/lun1 from
snapshot: abort_snap_restore successful
6719: BEGIN 15:52:47 03/09/04 SFSR of LUN: /vol/vol1/lun2 from
snapshot: abort_snap_restore
6719: END 15:52:47 03/09/04 SFSR of LUN: /vol/vol1/lun2 from
snapshot: abort_snap_restore successful
----