---
permalink: aix/concept_storageprovisioning_withsnapdrive_for_unix.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, operation 
summary: SnapDrive for UNIX は、エンドツーエンドのストレージ管理機能を提供します。ホストからストレージシステムにストレージをプロビジョニングし、ホストの論理ボリュームマネージャ \ （ LVM \ ）を使用するかどうかに関係なく、そのストレージを管理できます。 
---
= SnapDrive for UNIX でのストレージ処理
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX は、エンドツーエンドのストレージ管理機能を提供します。ホストからストレージシステムにストレージをプロビジョニングし、そのストレージを論理ボリュームマネージャ（ LVM ）を使用することも使用しなくても管理することもできます。

SnapDrive for UNIX では、次のストレージ操作を実行できます。

* LUN 、ファイルシステム、論理ボリューム、およびディスクグループを作成してストレージを作成します。
* ストレージに関する情報を表示します。
* ストレージに接続します。
* ストレージのサイズを変更する。
* ストレージから切断します。
* ストレージを削除します。


SnapDrive storage create コマンドを使用してストレージを作成すると、 SnapDrive for UNIX は、ホストの準備、検出マッピングの実行、作成した各 LUN への接続など、 LUN のセットアップに必要なすべてのタスクを自動的に実行します。SnapDrive storage show コマンドを使用すると、作成したネットアップ LUN 、ディスクグループ、ホストボリューム、ファイルシステム、または NFS ディレクトリツリーに関する情報を表示できます。

SnapDrive storage connect コマンドを使用すると、ストレージを新しい場所にマッピングできます。このコマンドを使用すると、作成に使用したホストとは別のホストから既存のストレージにアクセスできます。SnapDrive storage connect コマンドを使用すると ' 既存の LUN' ファイル・システム ' ディスク・グループ ' 論理ボリュームを新しいホストからアクセス可能にできますこれは、新しいホストから別のホストにストレージエンティティをバックアップする場合に便利です。

SnapDrive storage resize コマンドを使用すると、次の方法でストレージのサイズを拡張できます。

* ホストエンティティのアクセス先となるターゲットサイズを指定します
* ストレージの拡張に使用する一連のバイト数を入力します


ストレージを現在の場所にマッピングする必要がなくなった場合は、 SnapDrive storage disconnect コマンドを使用できます。このコマンドは、 1 つ以上のホストの場所から、その場所のストレージを作成している LUN へのマッピングを削除します。

ストレージを削除するには、 SnapDrive storage delete コマンドを使用します。SnapDrive for UNIX を使用すると、指定したホスト側のエンティティ、および基盤となるすべてのエンティティとそれらに関連付けられている LUN が削除されます。
