---
permalink: aix/concept_informationrequired_forusing_the_snapdrive_snaprestore_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, restore, command, information, required 
summary: Snapshot コピーをリストアするには、リストアするストレージエンティティを決定し、 Snapshot コピーの名前を指定します。 
---
= SnapDrive snap restore コマンドの使用に必要な情報
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーをリストアするには、リストアするストレージエンティティを決定し、 Snapshot コピーの名前を指定します。

次の表に、 SnapDrive snap restore コマンドの使用時に入力する必要がある情報を示します。

|===
| 要件 / オプション | 引数 


 a| 
リストアするストレージエンティティのタイプを決定し、該当する引数を指定してそのエンティティの名前を入力します。

* リストア対象のホスト・ボリュームまたはファイル・システムを指定すると、指定した引数は、この引数を含むディスク・グループに変換されます。SnapDrive for UNIX を使用すると、ディスク・グループ全体がリストアされます。SnapDrive for UNIX では、これらのディスク・グループ内のホスト・ボリュームのファイルシステムをフリーズし、これらのディスク・グループの LUN を含むすべてのストレージ・システム・ボリュームの Snapshot コピーを作成します。
* NFS マウントポイントであるファイル仕様を指定した場合、引数はディレクトリツリーに変換されます。SnapDrive for UNIX では、 NFS ディレクトリツリーまたはファイルのみがリストアされます。ディレクトリツリー内で、 SnapDrive for UNIX を使用すると、 Snapshot コピーの作成後に作成した新しい NFS ファイルまたはディレクトリがすべて削除されます。これにより、リストアされたディレクトリツリーの状態が、ツリーの Snapshot コピー作成時と同じになります。
* LUN をリストアすると、 SnapDrive for UNIX によって指定した LUN がリストアされます。
* LUN で直接作成されたファイルシステムをリストアする場合、 SnapDrive for UNIX によって LUN とファイルシステムがリストアされます。
* Snapshot コピーに、複数のストレージシステムボリュームにまたがるストレージエンティティが含まれている場合、その Snapshot コピー内の任意のエンティティをリストアできます。




 a| 
LUN （ `-lun_file_spec_` ）
 a| 
LUN の名前。ストレージシステム、ボリューム、および LUN の名前を含める必要があります。 _



 a| 
ディスク・グループ（ dg_file_spec_c ）またはボリューム・グループ（ g-vg_file_spec_` ）
 a| 
_name には、ディスクまたはボリュームグループの名前を指定します



 a| 
ファイルシステム (`-fs_file_spec_`)
 a| 
_ ファイルシステムの _ 名



 a| 
ファイル (`-file_file_spec_`)
 a| 
_ NFS ファイルの _ 名



 a| 
ホスト・ボリューム (`-hostvol_file_spec_`) または論理ボリューム (`-lvol_file_spec_`)
 a| 
_ ホストまたは論理ボリュームの名前要求されたボリュームとそのボリュームが含まれているディスクグループの両方を指定する必要があります。たとえば、 -hostvol dg3/acct_volume._ のように指定します



 a| 
Snapshot コピーの名前を指定します。ローカル・ホストに現在存在するコマンドプロンプトで指定した引数のいずれかが _file_dspec_` である場合は ' 短い形式の Snapshot コピー名を使用できます

ホストに _file_name 引数が存在しない場合は、 Snapshot コピー名の長い形式を使用して、ストレージ・システム名、ボリューム名、 Snapshot コピー名を入力する必要があります。Snapshot コピーに長い名前を使用していて、コマンドプロンプトでパス名がストレージシステムやストレージボリュームの情報と一致しない場合、 SnapDrive for UNIX は失敗します。次に、長い Snapshot コピー名の例を示します。「 big_filer ： /vol/account_vol ： snap_20031115`

場合によっては '_FILE_spec_' 引数で指定された値がホスト上に存在しない可能性がありますたとえば ' ファイル・システムをアンマウントした場合や ' エクスポート ' 移植解除 ' または削除によってディスク・グループを削除した場合でも ' そのファイル・システムまたはディスク・グループは '_file_spec_' 引数の値になる可能性がありますただし、存在しない値とみなされます。SnapDrive for UNIX では ' 存在しない `_file_spec_` の Snapshot コピーをリストアできますが ' 長い Snapshot コピー名を使用する必要があります

SnapDrive for UNIX では、複数のストレージ・システムおよびボリュームにまたがる Snapshot コピーをリストアする際に、存在しない「 _FILE_spec 」引数を使用すると、コマンド・ラインで不整合が発生することがあります。既存の `_file_spec_` 引数は許可されません複数のストレージシステムの Snapshot コピーからストレージエンティティを 1 つだけリストアする場合は、ストレージエンティティが含まれているストレージシステムと同じストレージシステム上に指定する必要はありません。

同じ Snapshot コピー名の省略形を使用すると、ストレージ・システムおよびストレージ・システム・ボリューム名は省略されるため、「 _snap_20031115_ 」と表示されます



 a| 
Snapshot コピー名（ snapname ）
 a| 
`_snap_name_`



 a| 
「 _mysnap1_` 」のような短い名前、またはストレージ・システム名、ボリューム名、 Snapshot コピー名を含む長い名前のどちらかです。

一般的には、短縮名を使用することを推奨します。引数 `_file_spec_` が存在しない場合 : つまり ' ホスト上に存在しない場合 '_file_spec_' 引数の説明を参照してくださいそのあとで、 Snapshot コピーに長い名前を使用する必要があります。



 a| 
`-reserve|-noreserve `
 a| 



 a| 
オプション： Snapshot コピーのリストア時に SnapDrive for UNIX でスペースリザベーションを作成する場合



 a| 
「 -force 」を使用します
 a| 
~



 a| 
-noprompt`
 a| 
~



 a| 
オプション：既存の Snapshot コピーを上書きするかどうかを指定します。このオプションを指定しないと、既存の Snapshot コピーの名前を指定した場合に処理が停止します。このオプションで既存の Snapshot コピーの名前を指定すると、 Snapshot コピーを上書きするかどうかの確認を求められます。SnapDrive for UNIX がプロンプトを表示しないようにするには '-nofrt' オプションも指定します( -noprompt オプションを使用する場合は '-force オプションを必ず指定する必要があります )

最後の Snapshot コピー以降に構成が変更されたディスク・グループをリストアする場合は ' コマンド・プロンプトに -force オプションを含める必要がありますたとえば ' スナップショット・コピーを作成してからデータがディスク上でストライプされる方法を変更した場合は '-force オプションを含める必要があります「 -force 」オプションを指定しない場合、この操作は失敗します。このオプションを使用すると '-noprompt' オプションを指定しない限り ' 操作を続行するかどうかを確認するメッセージが表示されます


NOTE: LUN を追加または削除した場合は '-force オプションを指定しても ' リストア処理に失敗します



 a| 
「トップ」
 a| 
~



 a| 
* オプション： * ファイルシステムを作成する場合は、次のオプションを指定できます。

* ホスト・マウント・コマンドに渡すオプションを指定するには '-mntopts' を使用します（たとえば ' ホスト・システム・ロギング動作を指定する場合）指定したオプションは、ホストファイルシステムのテーブルファイルに保存されます。使用できるオプションは、ホストファイルシステムのタイプによって異なります。
* 引数「 --mntopts_` 」は、 mount コマンドの「 -o 」フラグで指定されたファイルシステムの「 -type 」オプションです。引数に -o フラグを含めないでくださいたとえば、シーケンス -mntopts tmplog は、文字列「 -o tmplog 」を「 m ount 」コマンドに渡し、テキスト tmplog を新しいコマンドラインに挿入します。
+

NOTE: ストレージおよびスナップ操作に無効な '--mntopts_' オプションを渡した場合 'UNIX 用 SnapDrive はこれらの無効なマウントオプションを検証しません



|===