---
permalink: aix/reference_informationrequired_for_the_storagecreate_operation.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, create, command, operation, required 
summary: ストレージ作成処理が完了したら、いくつかの情報を指定する必要があります。 
---
= ストレージ作成処理に必要な情報
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ作成処理が完了したら、いくつかの情報を指定する必要があります。

次の表に、 SnapDrive storage create コマンドを使用してストレージを作成するときに入力する必要がある情報を示します。

|===
| 要件 | 引数 


 a| 
プロビジョニングするストレージのタイプを決定します。入力したコマンドに基づいて、次のいずれかを作成できます。

* LUN
+
1 つ以上の LUN を作成する場合は、最初の引数で LUN 名の長い形式を使用する必要があります。長い形式の LUN 名には、ストレージシステム名、ボリューム名、ボリューム内の LUN の名前を指定します。

+
追加の LUN を指定する場合は、新しい LUN が以前の LUN と同じストレージ・システムおよびボリューム上にある場合に、 LUN 名（省略名）を単独で使用できます。それ以外の場合は、新しいストレージ・システム名とボリューム名（またはボリューム名）を指定して以前の値を置き換えることができます。

* LUN 上に直接作成されるファイルシステム
+
LUN 上にファイル・システムを作成する場合 ' 最初の引数は '-fs' マウント・ポイントでなければなりませんストレージ・システムとボリュームの LUN にファイル・システムを作成するには '____fileervol_' 引数を使用して ' ストレージ・システムとボリュームの名前を指定します特定の LUN 上にファイル・システムを作成するには '--lun_' 引数を使用して ' ストレージ・システム名 ' ボリューム名 ' および LUN 名を指定しますまた、ホスト LVM をアクティブ化せずに LUN 上にファイルシステムを作成するには、「 -nolvm 」オプションも指定する必要があります。

+
デフォルトでは、 SnapDrive for UNIX は、 LUN のホストの準備と検出に関連するすべてのタスクに加え、マッピングと接続を自動的に実行します。

* ホストボリュームとファイルシステムを含む LVM ディスクグループ
+
ディスクまたはボリュームグループ、ファイルシステム、またはホストまたは論理ボリュームを指定すると、 SnapDrive for UNIX は、指定したエンティティの作成に必要なすべての操作を実行します。LUN は明示的に指定するか、ストレージシステムとボリュームの情報を提供するだけで、 SnapDrive for UNIX で自動的に作成されます。

+
ファイルシステムなどのエンティティを作成する場合、ディスクやボリュームグループの値を指定する必要はありません。SnapDrive for UNIX では、自動的に作成されます。





 a| 
* LUN （ -lun ）

 a| 
'*long_lun_name *



 a| 
* LUN を追加します

 a| 
`*LUN_name*` ( ロングまたはショートフォーム )



 a| 
* ディスク・グループ（ dg * dgname * ）またはボリューム・グループ（ vg * vgname * ）

 a| 
'*disk*' または '*volume group name*



 a| 
SnapDrive for UNIX では '-ddg オプションを指定して入力した値に基づいて 'LUN を保持するディスクまたはボリューム・グループを作成しますグループに指定する名前が存在していない必要があります。



 a| 
* ホスト・ボリューム (`-hostvol*file_spec*') または論理ボリューム (`-lvol*file_spec*`)

 a| 
'*Host*' または '*logical volume name*



 a| 
* ファイルシステム (`-fs*file_spec*`)

 a| 
'*filesystem_name*'



 a| 
「 -nolvm 」と入力します
 a| 
~



 a| 
* 必須： LUN 上に直接存在するファイル・システムを作成する場合は '-nolvm' オプションを指定します



 a| 
* LUN サイズ（ -lunsize' ）

 a| 
「 * size * 」と入力します



 a| 
* ディスクグループサイズ (`-dgsize')
* ボリューム・グループ・サイズ（ -vgsize ）

 a| 
「 * size * 」と入力します



 a| 
作成する各エンティティのサイズをバイト単位またはその他のデータ単位で指定します。LVM エンティティのサイズは、要求した LUN のアグリゲートサイズによって異なります。

ホスト・エンティティのサイズを制御するには '-dgsize' オプションを使用して ' 基盤となるディスク・グループのサイズをバイト単位で指定します



 a| 
* ストレージ・システム・ボリュームへのパス（ -fileervol` ）

 a| 
'*long_filer_path*



 a| 
* 「 -lun' 」と入力します

 a| 
'*long_lun_path *



 a| 
SnapDrive for UNIX で LUN を自動的に作成するストレージ・システムとそのボリュームを指定します。

* LUN を作成するストレージ・システムおよびボリュームを指定するには '-filol` オプションを使用します
+
LUN を指定しないでください。SnapDrive for UNIX では、 SnapDrive storage create コマンドのこの形式を使用すると、自動的に LUN が作成されます。LUN ID と各 LUN のサイズは、システムデフォルトを使用して決定されます。関連付けられたディスク / ボリュームグループの名前は、ホストボリュームまたはファイルシステムの名前に基づいています。

* 使用する LUN に名前を付けるには '-lun' オプションを使用します




 a| 
ファイル・システム・タイプ（「 -fstype 」）
 a| 
「 * type * 」と入力します



 a| 
ファイルシステムを作成する場合は、ファイルシステムタイプを表す文字列を指定します。

AIX の場合、 SnapDrive for UNIX は「 JFS2 」または「 vxfs 」を受け入れます。


NOTE: AIX ホストでは、ストレージ操作では JFS ファイルシステムタイプはサポートされていませんが、スナップショット操作ではサポートされています。


NOTE: デフォルトでは、 SnapDrive for UNIX は、ホストプラットフォームにファイルシステムタイプが 1 つしかない場合にこの値を提供します。その場合は入力する必要はありません。



 a| 
「 -vmtype 」と入力します
 a| 
「 * type * 」と入力します



 a| 
* オプション： SnapDrive for UNIX 操作に使用するボリューム・マネージャのタイプを指定します。



 a| 
「 -fsopts 」
 a| 
'*' オプション名と値 *



 a| 
「 -mntopts 」と入力します
 a| 
'*' オプション名と値 *



 a| 
「 -nopersist` 」
 a| 
~



 a| 
`-reserve|-noreserve `
 a| 
~



 a| 
* オプション： * ファイルシステムを作成する場合は、次のオプションを指定できます。

* ファイル・システムの作成に使用する host コマンドに渡すオプションを指定するには 'fsopts を使用しますたとえば、「 mkfs 」コマンドで使用するオプションを指定できます。通常、指定する値は引用符で囲んだ文字列である必要があり、コマンドに渡すテキストを正確に含める必要があります。
* ホスト・マウント・コマンドに渡すオプションを指定するには '-mntopts' を使用します（たとえば ' ホスト・システム・ロギング動作を指定する場合）指定したオプションは、ホストファイルシステムのテーブルファイルに保存されます。使用できるオプションは、ホストファイルシステムのタイプによって異なります。
+
「 -mntopts 」引数は、「 m ount 」コマンドの「 -o 」フラグで指定されたファイルシステムの「 -type 」オプションです。引数「 --mntopts_` 」に「 -o 」フラグを含めないでください。たとえば、シーケンス「 -mntopts tmplog 」は、文字列「 -o tmplog 」を「 m ount 」コマンドに渡し、テキスト tmplog を新しいコマンドラインに挿入します。

+

NOTE: ストレージおよびスナップ操作に無効な '--mntopts_' オプションを渡した場合 'UNIX 用 SnapDrive はこれらの無効なマウントオプションを検証しません

* ホスト上のファイル・システム・マウント・テーブル・ファイルにエントリを追加せずに ' -nosist' を使用してファイル・システムを作成しますデフォルトでは、 SnapDrive storage create コマンドは永続マウントを作成します。AIX ホスト上に LVM ストレージエンティティを作成すると、 SnapDrive for UNIX によってストレージが自動的に作成され、ファイルシステムがマウントされ、ホストファイルシステムテーブルにそのファイルシステムのエントリが格納されます。
* -reserve |-noreserve を使用して、スペース・リザベーションを作成するかどうかに関係なく、ストレージを作成します。




 a| 
* igroup 名（「 * -igroup * 」）

 a| 
`*ig_name*`



 a| 
* オプション： * igroup 名を指定する代わりに、デフォルトの igroup を使用することを推奨します。

|===