---
permalink: aix/reference_informationrequired_forusing_the_snapdrive_storagedelete_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, delete, command, required 
summary: SnapDrive storage delete コマンドを使用するには、いくつかの情報を指定する必要があります。この情報は、コマンドを正しく使用する場合に役立ちます。 
---
= SnapDrive storage delete コマンドを使用するために必要な情報を示します
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive storage delete コマンドを使用するには、いくつかの情報を指定する必要があります。この情報は、コマンドを正しく使用する場合に役立ちます。

|===
| 要件 | 引数 


 a| 
入力したコマンドに基づいて、次の種類のストレージを削除できます。

* LUN
+
ストレージシステムから削除する LUN を 1 つ以上指定してください。

+
1 つ以上の LUN を削除する場合は、最初の引数で LUN 名の長い形式を使用する必要があります。長い形式の LUN 名には、ストレージシステム名、ボリューム名、ボリューム内の LUN の名前を指定します。

+
追加の LUN を指定する場合は、新しい LUN が以前の LUN と同じストレージシステムおよびボリュームにある場合に、 LUN 名を単独で使用できます。それ以外の場合は、新しいストレージ・システム名とボリューム名（またはボリューム名）を指定して以前の値を置き換えることができます。

* LUN 上に直接作成されるファイルシステム
* ディスクまたはボリュームグループ
* ディスクまたはボリュームグループ上のファイルシステム
* ホストまたは論理ボリューム


filespec 引数に入力する値によって、削除するストレージエンティティを特定する必要があります。



 a| 
LUN （「 -lun' 」）
 a| 
`_long_lun_name_`



 a| 
LUN を追加します
 a| 
`_lun_name_`( ロングまたはショートフォーム )



 a| 
ディスク・グループ（ dg_file_spec_` ）またはボリューム・グループ（ g-vg_file_spec_` ）
 a| 
ディスクグループまたはボリュームグループの名前



 a| 
ファイルシステム (`-fs_file_spec_`)
 a| 
`_filesystem_name_`



 a| 
ホスト・ボリューム (`-hostvol_file_spec_`) または論理ボリューム (`-lvol_file_spec_`)
 a| 
ホストボリュームまたは論理ボリュームの名前


NOTE: 要求されたボリュームとそのボリュームを含むディスクグループの両方を指定する必要がありますたとえば '-hostvol dg3/acct_volume' のように指定します



 a| 
コマンド・プロンプトで指定したストレージを SnapDrive for UNIX で削除する場合 '1 つまたは複数のホスト・ボリュームを持つディスク・グループなど ' 他のエンティティを持つホスト側エンティティをコマンド・プロンプトに -full' オプションを指定します

このオプションを指定しない場合は、空のホスト側エンティティのみを指定する必要があります。



 a| 
「 -full` 」
 a| 
~



 a| 
ストレージを削除する共有ホストエンティティを指定するには、次の手順を実行します。



 a| 
「 -fstype 」を入力します
 a| 
「 _TYPE_` 」



 a| 
「 -vmtype 」と入力します
 a| 
「 _TYPE_` 」



 a| 
* オプション： SnapDrive for UNIX 操作に使用するファイルシステムとボリュームマネージャのタイプを指定します。

|===