---
permalink: aix/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, multipathing, hba 
summary: 'SnapDrive for UNIX でマルチパスを使用するには、 HBA のインストールと起動を含む手順を完了する必要があります。NetApp 以外のマルチパス解決策を使用している場合は "HBA ベンダーの Web サイトからソフトウェアとアプリケーションのパッケージをダウンロードする必要があります' 
---
= マルチパスの有効化
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX でマルチパスを使用するには、 HBA のインストールと起動を含む手順を完了する必要があります。ネットアップ以外のマルチパス解決策を使用している場合は、 HBA ベンダーの Web サイトからソフトウェアとアプリケーションのパッケージをダウンロードする必要があります。

システムで FC および iSCSI の最新バージョンのシステムコンポーネントが実行されている必要があります。

http://mysupport.netapp.com/matrix["NetApp Interoperability Matrix Tool で確認できます"]

.手順
. 適切な Host Utilities ソフトウェアをインストールする前に、サポートされている HBA をインストールしてください。
+

NOTE: SnapDrive for UNIX はマルチベンダー HBA をサポートします。

. HBA サービスを開始します。
+
HBA サービスが実行されていない場合は、 SnapDrive for UNIX コマンド（ SnapDrive storage create や SnapDrive config prepare LUN' など）を実行すると、次のエラー・メッセージが表示されます。

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
必要な数のパスが動作していることを確認する必要があります。sanlun ユーティリティを使用してパスを検証できます。このユーティリティは、 Host Utilities ソフトウェアに含まれています。たとえば、 FC マルチパス構成では、「 lun fcp show adapter -v 」コマンドを使用できます。

+
次の例では、動作可能な（ポート状態）ホストに 2 つの HBA ポート（ fcd0 および fcd1 ）が接続されています。HBA または iSCSI イニシエータは 1 つだけ使用でき、ターゲット LUN へのパスを複数設定することでマルチパスを設定する必要があります。

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
ホストでマルチパスが有効になっている場合は、同じ LUN から複数のパスが認識されます。「 lun lun lun show all 」コマンドを使用してパスを確認できます。次の例では、同じ LUN への複数のパス（「 fish:/vol/vol1/LUN」 ）を検索できます。

+
[listing]
----
filer:         lun-pathname        device filename  adapter    protocol   lun size              lun state
    filer_1:        fish/vol/vol1/l1      hdisk36          fcs0       FCP       5m   (5242880)        GOOD
    filer_2:        fish/vol/vol0/lunKr   hdisk39          fcs0       FCP       100m (104857600)      GOOD
    filer_3:        fish/vol/vol0/testaix hdisk2           fcs0       FCP       200m (209715200)      GOOD
    filer_4:        fish/vol/vol1/l1      hdisk45          fcs1       FCP       5m   (5242880)        GOOD
----
. FC 構成で、スイッチのゾーニング設定を使用して、ホスト HBA ポートとターゲットポートをゾーニングします。
. 適切な FC スイッチまたは iSCSI スイッチを設置してセットアップします。
. SnapDrive で UNIX スタックの要件を確認します。
. SnapDrive for UNIX をインストールまたはアップグレードします。
. SnapDrive for UNIX のインストールを確認します。
. 「 napdrive.conf 」ファイルパスを探します。
. 「 napdrive.conf 」ファイルで次の設定変数を設定します。
+
** `_multipathing-type_`
** `_default-transport_`
** 「 _fstype_` 」
** `_vmtype_`
+
どのホストでも、マルチパスタイプ、転送タイプ、ファイルシステム、ボリュームマネージャのタイプは相互に依存します。次の表に、使用可能なすべての組み合わせを示します。



+
|===
| ホストプラットフォーム | デフォルトの転送タイプ | マルチパスタイプ | FSstype （英語） | vmtype を指定します 


 a| 
AIX の場合
 a| 
FCP
 a| 
ゼッタイ
 a| 
JFS2 または jfs
 a| 
LVM



 a| 
nativempio
 a| 
JFS2 または jfs
 a| 
LVM



 a| 
DMP
 a| 
VxFS の
 a| 
VxVM

|===
+
上記の表は '_multipathing-type_`'_default-transport_'`_fstype_`'_vmtype_` 構成変数のサポートされる値を示しています

. 「 napdrive.conf 」ファイルを保存します。
+
SnapDrive for UNIX では、起動するたびにこのファイルが自動的にチェックされます。変更を有効にするには、 SnapDrive for UNIX デーモンを再起動する必要があります。



* 関連情報 *

http://mysupport.netapp.com["ネットアップサポート"]

https://mysupport.netapp.com/NOW/products/interoperability["ネットアップの相互運用性"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["『 AIX Host Utilities 6.0 Installation and Setup Guide 』"]
