---
permalink: aix/task_enabling_and_disabling_log_files.html 
sidebar: sidebar 
keywords: snap, snapdrive, enable, disable, log, file 
summary: ログファイルを有効にする場合は、有効にするログファイルの名前と値のペアの値としてファイル名を指定します。ファイルを無効にする場合は、ログファイル名パラメータの値を入力しないでください。 
---
= ログファイルを有効または無効にします
:icons: font
:imagesdir: ../media/


[role="lead"]
ログファイルを有効にする場合は、有効にするログファイルの名前と値のペアの値としてファイル名を指定します。ファイルを無効にする場合は、ログファイル名パラメータの値を入力しないでください。

root ユーザとしてログインしておく必要があります。

.手順
. テキストエディタで 'napdrive.conf ファイルを開きます
. ログファイルを有効または無効にするオプションを選択します。
+
|===
| 状況 | 作業 


 a| 
* ログファイルを有効にします *
 a| 
有効にするログファイルの名前と値のペアの値としてファイル名を指定します。SnapDrive for UNIX は、書き込むファイルの名前が指定されている場合にのみログファイルを書き込みます。ログファイルのデフォルト名は次のとおりです。

** 監査ログ : 'daudit.log
** リカバリログ : 'd-recovery.log
** トレースログ : 'd-ctrace-log



NOTE: これらのファイルへのパスは、ホストオペレーティングシステムによって異なる場合があります。



 a| 
* ログファイルを無効にします *
 a| 
ログファイル名パラメータに値を入力しないでください。値を指定しないと、 SnapDrive for UNIX がログ情報を書き込むことのできるファイル名がありません。

* 例 * この例は、監査ログファイルを無効にします。'audit-log-file=""

|===
. すべての変更を行ったら 'napdrive.conf ファイルを保存します
+
SnapDrive for UNIX では、起動するたびにこのファイルが自動的にチェックされます。変更を有効にするには、 SnapDrive for UNIX デーモンを再起動する必要があります。


