---
permalink: aix/task_specifying_login_information.html 
sidebar: sidebar 
keywords: snap, snapdrive, specify, login, information 
summary: ストレージシステムのユーザログイン情報を指定する必要があります。ストレージシステムのセットアップ時に指定した内容に応じて、各ストレージシステムは同じユーザ名またはパスワード、あるいは一意のユーザ名またはパスワードを使用できます。すべてのストレージシステムが同じユーザ名またはパスワード情報を使用する場合は、次の手順を 1 回だけ実行する必要があります。ストレージシステムで一意のユーザ名またはパスワードを使用する場合は、ストレージシステムごとに次の手順を繰り返す必要があります。 
---
= ログイン情報を指定しています
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムのユーザログイン情報を指定する必要があります。ストレージシステムのセットアップ時に指定した内容に応じて、各ストレージシステムは同じユーザ名またはパスワード、あるいは一意のユーザ名またはパスワードを使用できます。すべてのストレージシステムが同じユーザ名またはパスワード情報を使用する場合は、次の手順を 1 回だけ実行する必要があります。ストレージシステムで一意のユーザ名またはパスワードを使用する場合は、ストレージシステムごとに次の手順を繰り返す必要があります。

root ユーザとしてログインしていることを確認します。

.手順
. 次のコマンドを入力します。
+
`* SnapDrive config set_user_name filername_[_ filername..._]*`

+
`_user_name_` は最初にセットアップしたときにそのストレージ・システムに指定されたユーザー名です

+
`_filername_` はストレージ・システムの名前です

+
`_[filername...]_ すべてのストレージ・システムに同じユーザ・ログインまたはパスワードが設定されている場合、 1 つのコマンド・ラインに複数のストレージ・システム名を入力できることを定義します。少なくとも 1 つのストレージシステムの名前を入力する必要があります。

. パスワードがある場合は、プロンプトでパスワードを入力します。
+

NOTE: パスワードが設定されていない場合は、パスワードの入力を求められたら Enter キーを押します。

+
次に、 toaster というストレージ・システム用に「 root 」というユーザを設定する例を示します。

+
[listing]
----
# snapdrive config set `root` toaster
Password for root:
Retype Password:
----
+
次の例では '3 つのストレージ・システム用に 'root' という名前の 1 つのユーザを設定します

+
[listing]
----
# snapdrive config set root toaster oven broiler
Password for root:
Retype Password:
----
. 別のユーザ名またはパスワードを持つ別のストレージ・システムを使用している場合は、この手順を繰り返します。

