---
permalink: solaris/concept_unable_to_restore_a_snapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, restore, snapshot, copy 
summary: SnapDrive snap restore コマンドによる Snapshot コピーのリストア機能に影響する条件は、次のとおりです。 
---
= Snapshot コピーをリストアできません
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive snap restore コマンドの Snapshot コピーのリストア機能に影響する条件は、ごくわずかです。

* SnapDrive snap restore コマンドは ' 次のタスクを実行できる必要があります
+
** すべてのディスクグループを照会して LUN のリストを表示します。
** SCSI コマンドを使用してすべての LUN を照会SnapDrive snap restore コマンドを正常に実行するために ' ホスト・ボリュームとファイル・システムを使用可能にしてマウントする必要はありません


* アクセス権限で、ホストがそのストレージシステム上の情報の Snapshot コピーを作成およびリストアできるようにする必要があります。
* マウントできるように、 NFS マウントディレクトリをホストに正しくエクスポートする必要があります。



NOTE: ディスクグループに対して LUN を追加または削除した場合は、必ず別の Snapshot コピーを作成してください。

* Snapshot コピーの作成後にホストボリュームまたはファイルシステムをディスクグループに追加し、その Snapshot コピーをリストアしようとすると、エラーメッセージが表示されます。このような状況でリストア処理を正常に実行するには ' コマンド・ラインに force オプション（ -f ）を含める必要があります
+

NOTE: Snapshot コピーの作成およびリストア時に、追加したホストボリュームとファイルシステムにはアクセスできなくなります。

* ホストボリュームまたはファイルシステムの名前を変更したり、 Snapshot コピーを作成したあとでマウントポイントを変更したりすると、リストア処理が失敗します。このような状況でリストア処理を正常に実行するには ' コマンド・ラインに force オプション（ -f ）を含める必要があります
+

NOTE: 上書きしないように意図した内容を誤って上書きしないようにするには、細心の注意を払って「 -f 」オプションを使用してください。

* Snapshot コピーの作成後に LUN の名前を変更した場合に、その Snapshot コピーをリストアしようとすると、リストア処理は失敗します。LUN の名前を変更したら、新しい Snapshot コピーを作成する必要があります。
+

NOTE: Snapshot のリストア処理を開始したら、停止しないでください。この処理を停止すると、システムが不整合な状態のままになる可能性があります。その場合は、手動によるリカバリが必要になることがあります。


