---
permalink: solaris/concept_informationrequired_forusing_the_snapdrive_storageconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, connect, command 
summary: SnapDrive storage connect コマンドを使用する際には、入力する必要がある情報がいくつかあります。この情報は、コマンドを正しく使用する際に役立ちます。 
---
= SnapDrive storage connect コマンドを使用するために必要な情報を示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive storage connect コマンドを使用する際には、入力する必要がある情報がいくつかあります。この情報は、コマンドを正しく使用する際に役立ちます。

|===
| 要件 | 引数 


 a| 
ホストに接続する LUN 、 LUN に直接作成されたファイルシステム、または LVM エンティティを指定します。

* 1 つ以上の LUN を接続する場合は、最初の引数で LUN 名の長い形式を使用する必要があります。長い形式の LUN 名には、ストレージシステム名、ボリューム名、ボリューム内の LUN の名前を指定します。
+
追加の LUN を指定する場合は、新しい LUN が以前の LUN と同じストレージシステムおよびボリュームにある場合に、 LUN 名を単独で使用できます。それ以外の場合は、新しいストレージ・システム名とボリューム名（またはボリューム名）を指定して以前の値を置き換えることができます。

* LUN 上に直接作成されたファイルシステムを接続する場合は、長い形式の LUN 名と「 -nolvm 」オプションも含める必要があります。
* ディスク・グループ ' ホスト・ボリューム ' およびファイル・システムと LUN を接続する場合は '-fs' および -hostvol' オプションを使用して ' ファイル・システムとホスト・ボリュームを指定する必要がありますホストボリュームにディスクグループの名前が含まれている必要があります。




 a| 
LUN （「 -lun' 」）
 a| 
`_long_lun_name_`



 a| 
-lun' オプションで最初に指定する値には ' ストレージ・システム名 ' ボリューム名 'LUN 名を含める必要があります同じボリューム上の複数の LUN を接続するには ' 最初のパス名に完全な情報を入力した後で '-lun' オプションの相対パス名を使用しますSnapDrive for UNIX は、相対パス名を検出すると、前の LUN と同じボリューム上で LUN を検索します。同じボリューム上にない LUN を追加で接続するには、各 LUN への完全パス名を入力します。



 a| 
LUN を追加します
 a| 
`_lun_name_`( ロングまたはショートフォーム )



 a| 
`-fs` に与えられる `_file_spec_` は 'LUN 上に直接作成されたファイル・システムを接続するときのファイル・システム・マウントポイントの名前です



 a| 
ファイルシステム (`-fs file-spec')
 a| 
`_filesystem_name_`



 a| 
ホスト LVM をアクティブ化せずに、 LUN 上で作成されたファイルシステムを接続するため。



 a| 
「 -nolvm 」と入力します
 a| 



 a| 
ホストボリューム上のファイルシステムを接続するには、次の手順を実行します。

指定した `-fs_file_spec_` と -hostvol file_spec' は ' 新しいホストに接続する LVM ファイル・システム ' ディスク・グループ ' およびホスト・ボリュームを識別します

接続するストレージ階層には、ディスクグループ、ホストボリューム、およびファイルシステムが含まれている必要があります。「 -fs 」と「 -hostvol 」に値を指定する必要があります。「 -hostvol 」の値にはディスクグループの名前を指定する必要があります。



 a| 
ホスト・ボリューム（ --hostvol file-spec` ）
 a| 
「 _disk_group_name 」および「 _host_volume_name 」です



 a| 
オプション：ホスト・ファイル・システム・テーブルにエントリを作成することなく ' ストレージを新しい場所に接続するには '-nopersist' オプションを使用しますデフォルトでは、 storage connect コマンドによって永続的マウントが作成されます。つまり 'Solaris ホスト上に LVM ストレージエンティティを作成すると ' ストレージが SnapDrive for UNIX によって自動的に作成され ' ファイルシステムがマウントされ ' ホストファイルシステムテーブルにそのファイルシステムのエントリが格納されます



 a| 
「 -nopersist` 」
 a| 
~



 a| 
* オプション： * igroup 名を指定する代わりに、デフォルトの igroup を使用することを推奨します。



 a| 
igroup 名（「 -igroup 」）
 a| 
`_ig_name_`



 a| 
`__ デバイスタイプ _`
 a| 
~



 a| 
SnapDrive for UNIX の操作に使用するデバイスのタイプを指定します。これは ' ホスト・クラスタ全体としての LUN' ディスク・グループ ' ファイル・システムの範囲を指定する「共有」または LUN ' ディスク・グループ ' ファイル・システムの範囲をローカルとして指定する「専用」のいずれかです



 a| 
「 -fstype 」を入力します
 a| 
「 _TYPE_` 」



 a| 
「 vmtype 」
 a| 
「 _TYPE_` 」



 a| 
* オプション： SnapDrive for UNIX 操作に使用するファイルシステムとボリュームマネージャのタイプを指定します。



 a| 
「 -mntopts 」と入力します
 a| 
~



 a| 
* オプション： * ファイルシステムを作成する場合は、次のオプションを指定できます。

* ホスト・マウント・コマンドに渡すオプションを指定するには '-mntopts' を使用します（たとえば ' ホスト・システム・ロギング動作を指定する場合）指定したオプションは、ホストファイルシステムのテーブルファイルに保存されます。使用できるオプションは、ホストファイルシステムのタイプによって異なります。
* 引数「 --mntopt_` 」は、 mount コマンドの「 -o 」フラグで指定されたファイルシステムの「 -type 」オプションです。「 -mntopts 」引数に「 -o 」フラグを含めないでください。たとえば、シーケンス -mntopts tmplog は、文字列「 -o tmplog 」を「 m ount 」コマンドに渡し、テキスト tmplog を新しいコマンドラインに挿入します。
+

NOTE: ストレージおよびスナップ操作に無効な「 -mntops 」オプションを渡した場合、 SnapDrive for UNIX はそれらの無効なマウントオプションを検証しません。



|===