---
permalink: solaris/concept_guidelines_for_restoring_a_snapshot_copy_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, copy, host, restore 
summary: Snapshot コピーのリストア時には、次のガイドラインに従ってください。 
---
= ホストクラスタ環境での Snapshot コピーのリストアに関するガイドラインを参照してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーのリストア時には、次のガイドラインに従ってください。

* SnapDrive snapshot restore コマンドは ' ホスト・クラスタ内の任意のノードから実行できます
* ファイルシステムまたはディスクグループが稼働している場合は、そのファイルシステムまたはディスクグループをホストクラスタ内のすべてのノードで共有する必要があります。
* 共有ファイルシステムまたはディスクグループのいずれかの LUN がホストクラスタの外部のノードにマッピングされている場合、そのファイルシステムまたはディスクグループでの Snapshot リストア処理は失敗します。共有 LUN がホストクラスタの外部のノードにマッピングされていないことを確認します。
* Snapshot の作成処理は、専用のファイルシステムまたはディスクグループに対して実行できますが、 Snapshot コピーを共有モードでリストアする場合は、ホストクラスタ内のどのノード上でも、ファイルシステムまたはディスクグループが専用モードになっていないことを確認する必要があります。それ以外の場合は、 SnapDrive for UNIX でエラーが表示されます。
* ホストクラスタにファイルシステムまたはディスクグループが存在しない場合、 SnapDrive for UNIX は Snapshot コピーから LUN を作成し、それらをホストクラスタ内のすべてのノードにマッピングして、ディスクグループおよびファイルシステムをアクティブ化します。Veritas クラスタボリュームマネージャは、ホストクラスタ内のすべてのノードに LUN をマッピングすると、ホストクラスタ内のすべてのノード間で LUN 情報を更新します。クラスタノードの CVM インスタンス間で LUN 情報が更新される前にディスクグループのアクティブ化が試行されると、 Snapshot リストア処理が失敗する場合があります。CVM 更新の場合は、 SnapDrive snap restore コマンドを再発行する必要があります。
* ホストクラスタの外部のノードに作成された Snapshot コピーは、次の条件に該当する場合にのみ、クラスタ内でリストアおよび共有できます。
+
** ファイルシステムまたはディスクグループが、ホストクラスタ内のどのノードにも専用モードで存在しません。
** これらの LUN は、ホストクラスタの外部のノードには認識されません。


* 1 回の Snapshot リストア処理では、共有システムと専用システムの両方で Snapshot コピーをリストアすることはできません。
* 共有ディスク・グループまたはファイル・システムに -deviceType オプションを指定して SnapDrive snap restore コマンドを実行した場合 ' または -deviceType オプションを指定せずにコマンドを実行した場合は ' 複数のノードに接続されている LUN がリストアされたことを SnapDrive for UNIX が警告します
* Snapshot コピーの作成と Snapshot コピーのリストアの間にディスクグループの設定が変更されると、 SnapDrive for UNIX のアラートによって設定が変更されたことが通知されます。

