---
permalink: solaris/concept_informationrequired_forusing_the_snapdrive_snapconnect_command.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, command 
summary: Snapshot コピーに接続するには、ストレージエンティティの種類を確認し、 NFS ディレクトリツリーを使用して Snapshot コピーを Data ONTAP 7.3 構成に接続します。 
---
= SnapDrive snap connect コマンドの使用に必要な情報
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot コピーに接続するには、ストレージエンティティの種類を確認し、 NFS ディレクトリツリーを使用して Snapshot コピーを Data ONTAP 7.3 構成に接続します。

次の表に、 SnapDrive snap connect コマンドを使用するときに入力する必要がある情報を示します。


NOTE: 'snap connect' 操作には 'vximport' を使用する Solaris 上の Storage Foundation Enterprise ライセンスが必要です

|===
| 要件 / オプション | 引数 


 a| 
Snapshot コピーの接続に使用するストレージエンティティのタイプを決定し、そのエンティティの名前を適切な引数で指定します。これは '`_src_fspec_` 引数の値です

* LUN の Snapshot コピーを接続する場合は、指定した LUN が SnapDrive for UNIX で接続されます。コマンド・ラインで '-lun' オプションを使用するには '-vg`'-dgd`'`-fs'`lvol''-hostvol' オプションを指定しますLUN の省略形は、 lun_name または qtree_name / lun_name の形式で指定できます。
* LUN に直接作成されたファイルシステムの Snapshot コピーを接続する場合、 SnapDrive for UNIX はファイルシステムを含む LUN を接続します。
* ホストボリュームまたはファイルが指定されたディスクグループの Snapshot コピーを接続すると、引数がストレージシステム上の一連のディスクグループに変換されます。SnapDrive for UNIX では、エンティティが含まれているディスクグループ全体を接続します。これは、エンティティがホストボリュームまたはファイルシステムである場合も同様です。
* NFS ファイルシステムの Snapshot コピーを接続すると、引数は NFS ディレクトリツリーに変換されます。SnapDrive for UNIX では、ボリュームの FlexClone が作成され、 Snapshot コピーで指定されていないディレクトリツリーが削除され、 NFS ディレクトリツリーが接続されてマウントされます。NFS マウント・ポイントを指定する場合は ' 同じコマンド・ラインで非 NFS エンティティー（ -vg`'-dgd`'`-fs'`-lvol'-hostvol ）を指定することはできません
+

NOTE: SnapDrive for UNIX では、マウントポイントレベルでのシンボリックリンクはサポートされていません。





 a| 
LUN （ `-lun_file_spec_` ）
 a| 
_ LUN の略称。 _



 a| 
`s_lun_name_` には 'snapname_long_snap_name_` に存在する LUN を指定します短縮形の LUN_name が必要です。ストレージシステムまたはストレージシステムボリュームの名前は指定できません。`_d_lun_name_` は、 LUN が接続されている名前を指定します。省略形の「 _LUN_name_ 」は必須です。ストレージシステムまたはストレージシステムボリュームの名前は指定できません。「 _d_lun_name_` 」を指定する必要があります



 a| 
ディスク・グループ（ dg_file_spec_` ）またはボリューム・グループ（ g-vg_file_spec_` ）
 a| 
_name には、ディスクまたはボリュームグループの名前を指定します



 a| 
ファイルシステム (`-fs_file_spec_`)
 a| 
_ ファイルシステムの _ 名



 a| 
ホスト・ボリューム (`-hostvol_file_spec_`) または論理ボリューム (`-lvol_file_spec_`)
 a| 
_ ホスト名または論理ボリューム _



 a| 
NFS ディレクトリツリーを使用して Data ONTAP 7.3 構成に Snapshot コピーを接続する。

* Data ONTAP 7.3 以降のバージョンの Data ONTAP と従来の（ FlexVol ではなく）ボリュームを使用する設定の場合、このオプションを指定して、 Snapshot コピーを読み取り専用アクセスで接続する（必須）必要があります。
* Data ONTAP 7.3 以降および FlexVol ボリュームを使用している構成では、 SnapDrive for UNIX が自動的に読み取り / 書き込みアクセスを提供します。このオプションは、アクセスを読み取り専用に制限する場合にのみ指定します（オプション）。




 a| 
- 読み取り専用
 a| 
読み取り専用アクセス権の設定 _



 a| 
オプション：ストレージエンティティが接続されたあとにターゲットエンティティにアクセスする際に使用する名前を指定します。SnapDrive for UNIX では、この名前を使用してデスティネーションエンティティが接続されます。これは 'dest_file_spec_` 引数です

この名前を省略した場合 'snap connect コマンドは '_src_fspec_` に指定した値を使用します



 a| 
ターゲットエンティティの名前
 a| 
`_ddest_file_spec_`



 a| 
オプション：デスティネーションストレージエンティティの名前を指定します。この情報を 'dest_fspec/src_fspec_' ペアの一部として含めた場合は ' ここに入力する必要はありません

デスティネーション・ストレージ・エンティティの名前を指定するには '-dest_fspec/src_fspec_` ペアの一部でない場合に '-destxx オプションを使用しますたとえば '-fs' オプションでは ' デスティネーション・マウント・ポイントのみを指定するため '-ddestdg オプションを使用してデスティネーション・ディスク・グループを指定できます

ターゲット・ディスク・グループ内のエンティティの接続に必要な名前を指定しない場合 ' SnapDrive snap connect コマンドはソース・ディスク・グループから名前を取得します

移動先ディスクグループのエンティティを接続するために必要な名前を指定しない場合、「 snap connect コマンド」はソースディスクグループから名前を取得します。その名前を使用できない場合 ' コマンド・プロンプトに --autorname' を指定しない限り ' 操作は失敗します



 a| 
デスティネーション・ディスク・グループ（ -destddg ）またはデスティネーション・ボリューム・グループ（ -destvg ）
 a| 
`_dgname_`



 a| 
デスティネーション論理ボリューム (`-ddestlv') またはデスティネーション・ホスト・ボリューム (`-desthv`)
 a| 
`_lvname_`



 a| 
Snapshot コピーの名前を指定します。ストレージ・システム名、ボリューム名、 Snapshot コピー名を入力する場合は、長い形式の名前を使用します。



 a| 
Snapshot コピー名（ snapname ）
 a| 
`_long_snap_name_`



 a| 
「 -nopersist` 」
 a| 
~



 a| 
オプション：ホストファイルシステムテーブルにエントリを作成せずに、 Snapshot コピーを新しい場所に接続します。

* -nosist` オプションを使用すると ' ホスト・ファイル・システム・テーブルにエントリを作成することなく ' スナップショット・コピーを新しい場所に接続できますSnapDrive for UNIX のデフォルトでは、永続マウントが作成されます。つまり、次のことが可能です。
+
** Solaris ホストで Snapshot コピーを接続すると 'UNIX 用 SnapDrive によってファイル・システムがマウントされ ' ホストのファイル・システム・テーブルにファイル・システムを構成する LUN のエントリが作成されます
** NFS ディレクトリ・ツリーを含む Snapshot コピーを接続する場合には '-nosist' を使用できません






 a| 
`-reserve|-noreserve `
 a| 
~



 a| 
オプション：スペースリザベーションを作成するかどうかに関係なく、 Snapshot コピーを新しい場所に接続します。



 a| 
igroup 名（「 -igroup 」）
 a| 
`_ig_name_`



 a| 
オプション： igroup 名を指定する代わりに、デフォルトの igroup を使用することを推奨します。



 a| 
-- 自動展開
 a| 
~



 a| 
ボリューム・グループへの接続時に入力する必要のある情報量を短縮するには ' コマンド・プロンプトに -autoconfigure オプションを含めますこのオプションを使用すると、ボリュームグループ内の論理ボリュームまたはファイルシステムのサブセットにのみ名前を付けることができます。その後、ディスクグループ内の残りの論理ボリュームまたはファイルシステムへの接続を拡張します。このようにして、各論理ボリュームやファイルシステムを指定する必要はありません。SnapDrive for UNIX では、この情報を使用してデスティネーションエンティティの名前を生成します。

このオプションでは、コマンドプロンプトで指定した各ディスクグループと、グループ内のすべてのホスト LVM エンティティが環境に設定されます。-autodomexpand オプション（デフォルト）を使用しない場合は ' ディスク・グループ全体を接続するために ' そのディスク・グループに含まれるすべての影響を受けるホスト・ボリュームとファイル・システムを指定する必要があります


NOTE: 入力した値がディスクグループの場合は、ディスクグループの接続先を SnapDrive for UNIX が認識しているため、すべてのホストボリュームまたはファイルシステムを入力する必要はありません。

このオプションを指定する場合は、 -autorname` オプションも指定することを推奨します。-autostoexpand オプションで LVM エンティティのコピー先を接続する必要があるが ' 名前がすでに使用されている場合は '-autorname' オプションがコマンド・プロンプトにない限り ' コマンドは失敗します



 a| 
コマンドプロンプトで参照されるすべてのディスクグループ（ホストボリューム自体またはファイルシステムの指定）で LVM ホストボリュームの一部を指定していないと、 -autoconfigure を省略した場合、コマンドは失敗します。



 a| 
`-autorname`
 a| 
~



 a| 
--autorename' オプションを指定せずに --autoexpand オプションを使用すると 'LVM エンティティのコピー先のデフォルト名が使用されている場合 'snap connect コマンドは失敗します-autorname' オプションを指定すると 'UNIX 用 SnapDrive は ' デフォルト名が使用中のときにエンティティの名前を変更しますこれは ' コマンド・プロンプトで -autorname' オプションを指定すると ' 必要な名前がすべて使用可能かどうかに関係なく ' スナップショット接続操作が続行されることを意味します

このオプションでは、コマンドプロンプトで指定したすべてのホスト側エンティティを環境します。

コマンド・プロンプトに --autorname' オプションを含めると ' そのオプションを含めない場合でも '-autoconfigure オプションが使用されます



 a| 
`-deviceType`
 a| 
~



 a| 
オプション： SnapDrive for UNIX の処理に使用するデバイスのタイプを指定します。これは ' ホスト・クラスタ全体としての LUN' ディスク・グループ ' ファイル・システムの範囲を指定する「共有」または LUN ' ディスク・グループ ' ファイル・システムの範囲をローカルとして指定する「専用」のいずれかです

--deviceType 専用オプションを指定した場合は 'UNIX 用の SnapDrive 2.1 で現在サポートされている SnapDrive snap connect コマンドのすべてのオプションが常に使用されているようになります

ホスト・クラスタ内の任意の非マスター・ノードから -deviceType shared オプションを指定して SnapDrive snap connect コマンドを開始すると ' コマンドはマスター・ノードに出荷され ' 実行されますこれを実現するには、 root ユーザの「 rsh 」または「パスワードなしのアクセス」プロンプトが、ホストクラスタ内のすべてのノードに対して設定されている必要があります。



 a| 
「 -split` 」
 a| 
~



 a| 
Snapshot 接続処理と Snapshot 切断処理の際に、クローンボリュームまたは LUN をスプリットできます。



 a| 
「トップ」
 a| 
~



 a| 
* オプション： * ファイルシステムを作成する場合は、次のオプションを指定できます。

* ホスト・マウント・コマンドに渡すオプションを指定するには '-mntopts' を使用します（たとえば ' ホスト・システム・ロギング動作を指定する場合）指定したオプションは、ホストファイルシステムのテーブルファイルに保存されます。使用できるオプションは、ホストファイルシステムのタイプによって異なります。
* 引数 -`_mntopts_` は 'mount コマンドの -o`flag を使用して指定されたファイルシステムの --type` オプションです引数「 --mntopts_` 」に「 -o 」フラグを含めないでください。たとえば、シーケンス -mntopts tmplog は、文字列「 -o tmplog 」を「 m ount 」コマンドに渡し、テキスト tmplog を新しいコマンドラインに挿入します。
+

NOTE: ストレージおよびスナップ操作に無効な「 -mntops 」オプションを渡した場合、 SnapDrive for UNIX はそれらの無効なマウントオプションを検証しません。



|===