---
permalink: solaris/concept_guidelines_for_storage_connection_in_a_host_cluster_environment.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, connect, host, cluster 
summary: ホストクラスタ環境で SnapDrive storage connect コマンドを使用する前に、いくつかのガイドラインに従う必要があります。 
---
= ホストクラスタ環境でのストレージ接続に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホスト・クラスタ環境で SnapDrive storage connect コマンドを使用する前に ' いくつかのガイドラインに従う必要があります

* 共有ディスクグループまたはファイルシステムを使用するホストクラスタ構成に新しいノードが追加された場合は、 SnapDrive storage connect-deviceType shared-コマンド を使用します。SnapDrive ストレージ接続処理は、ホストクラスタ内の任意のノードから実行できます。
* ストレージ接続処理が成功するためには、次の処理は行わないでください。
+
** ストレージエンティティがホストクラスタ内のどのノードにも存在しないようにしてください。
** LUN をホストクラスタ内のどのノードにもマッピングしないでください。


* デフォルト値は dedicated であるため ' 特定のノード上のストレージ・エンティティに接続するには '-deviceType dedicated オプションを使用するか ' コマンド・ライン構文で -deviceType オプションを省略します
* Veritas File System （ VxFS ）で Veritas Volume Manager を使用するディスクグループでは、ファイルシステムのホストクラスタ全体のストレージ接続がサポートされています。この操作は raw LUN ではサポートされていませんつまり '-nolvm' オプションはサポートされていません
* 「 -igroup 」オプションは、 SnapDrive storage connect コマンドではサポートされていません。
* 次のいずれかに該当する場合、ストレージ接続処理は失敗します。
+
** ストレージエンティティの接続処理中にエラーが発生した場合。SnapDrive for UNIX は、ホストクラスタ内のマスターノードからこの処理を実行します。共有ストレージエンティティを作成する前に、 LUN を作成し、マスターノードに LUN をマッピングして、すべての非マスターノードに LUN をマッピングします。SnapDrive for UNIX では、すべてのノードの igroup を内部的に作成および管理します。
** クラスタボリュームマネージャ（ CVM ）を開始する前にホストクラスタ内のノードがシャットダウンしてリブートした場合は、 LUN で使用される共有ディスクグループをノードで検出する必要があります。デフォルト SnapDrive では、 FC ポート・アドレスが変更されていない場合、 LUN は表示されます。変更されていない場合は、 lun storage connect コマンドを使用して LUN をマッピングする必要があります。


* 専用のストレージエンティティデータで作成され、その後切断された LUN 上にあるストレージエンティティを使用して、共有ストレージ接続処理を実行できます。これは、ストレージエンティティがどのホストクラスタノードにも存在しない場合にのみです。
* 現在のノードがホストクラスタの一部でない場合、またはストレージエンティティがホストクラスタに存在しない場合にのみ、共有ストレージエンティティのメタデータを含む LUN 上のストレージエンティティに対して専用のストレージ接続処理を実行できます。

