---
permalink: solaris/concept_splitting_the_volume_or_lun_clone_operations.html 
sidebar: sidebar 
keywords: snap, snapdrive, split, volume, clone, lun 
summary: SnapDrive for UNIX では、ボリュームクローンまたは LUN クローンをスプリットできます。クローンスプリットが完了すると、親ボリュームとクローンの関係が破棄され、両方のエンティティが相互に独立していて、それぞれのストレージスペースがあります。 
---
= ボリュームクローンまたは LUN クローンをスプリットします
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX では、ボリュームクローンまたは LUN クローンをスプリットできます。クローンスプリットが完了すると、親ボリュームとクローンの関係が破棄され、両方のエンティティが相互に独立していて、それぞれのストレージスペースがあります。

クローンスプリット処理は次のとおりです。

* ボリュームクローンまたは LUN クローンのディスクスペースを概算します（ MB 単位）。
* ボリュームクローンまたは LUN クローンをスプリットします。
* ボリュームクローンまたは LUN クローンスプリットを停止します。
* 実行中、完了、または失敗したクローンスプリットのステータスを表示します。


[NOTE]
====
* ボリュームクローンをスプリットすると、クローンボリューム内のすべての Snapshot コピーが削除されます。
* クローニングされたボリューム内に Snapshot コピーが作成されているかどうかを確認するには、ファイル仕様をスプリットする前に clone split estimate コマンドを実行する必要があります。
* すべてのクローン・スプリット・コマンドでは、長い LUN 名のみを「 -lun 」オプションで指定する必要があります。他のストレージ・エンティティ（ -vg 、 -dg 、 -fs 、 -lvol 、または -hostvol オプション）と同じコマンド・ラインで「 -lun' 」オプションを指定することはできません。
* clone split コマンドでは、ファイル指定の絶対パス名を必ず使用する必要があります。
* Snapshot を使用した LUN クローンスプリットの見積もりは、 SnapDrive 4.2 for UNIX 以降で作成された Snapshot コピーに対してのみ可能です。


====