---
permalink: solaris/reference_storage_provisioning_command_lines.html 
sidebar: sidebar 
keywords: snap, snapdrive, storage, command, line, provisioning 
summary: ストレージのプロビジョニングには、一部の SnapDrive for UNIX コマンドを使用します。 
---
= ストレージプロビジョニングのコマンドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージのプロビジョニングには、一部の SnapDrive for UNIX コマンドを使用します。

ストレージプロビジョニング処理に使用するコマンドラインオプションは次のとおりです。

|===
| 操作 | コマンドラインオプション 


 a| 
作成
 a| 
SnapDrive storage create -lun_long_lun_name_[_lun_name_...] -lunsize_[{-dg | -vg ｝ _dG_name_][-igroup ig_name_[_ig_name...] [{-reserve | -noreserve }] [-fstype_type_type_type_][-vmtype][-vmtype] [-dv



 a| 
SnapDrive storage create ｛ -lvol | -hostvol ｝ _file_spec_[｛ -dg | -vg ｝ dg_name] ｛ dgsize | -vgsize ｝ _size_ -fileervol_long_filer_path_[-deviceType ｛ shared | dedicated] [{-noreserve | -reserve }] [-fstype_type] [vmtype] [-d



 a| 
SnapDrive storage create -fs_file_spec_-nolvm [-fsopts options][-mntopts options][-nosist]{{-lun_long_lun_name_|-fileervol_long_filer_path_}-lunize_[-igroup _name_[-igroup _ig_name_or_ig_name...] -noltype [-dos] -vmfsott_servtype] -type|nodif_reserve|nodes[%1$t_se|node] -vmtype }-vmtype }-vm[-dos



 a| 
SnapDrive storage create _host_lvm_fspec _ -fileervol_long_filer_path_dgsize_[-igroup_ig_name_[_ig_name..._]] [{-reserve | -noreserve }] [-deviceType ｛ shared | dediced}]



 a| 
SnapDrive storage create _host_lvm_fspec _ -lun_long_lun_name _[_lun_name_...] -lunsize_[-igroup_ig_name_[_ig_name..._]] [{-reserve | -noreserve }] を実行します

[NOTE]
====
作成するストレージのタイプに応じて '-file_spec' 引数のいずれかの形式を使用できます( 「 -dg 」は「 -vg` 」の同義語であり、「 -hostvol 」は「 -lvol 」の同義語です ) 。

LUN 上に直接ファイルシステムを作成するには、次の形式を使用します： `-fs_file_spec_[-nolvm -fs_type_][-fsops_options_][-mntopts_options_][-vmtype_]`

ディスク・グループまたはホスト・ボリュームを使用するファイル・システムを作成するには ' 次の形式を使用します `-fs_file_spec_[-fstype_type_type_][-fsopts_options_][-mntops_options_][-hostvol_file_spec_][-dG_TYPE_vmtype_d`

論理ボリュームまたはホストボリュームを作成するには ' 次の形式を使用します [-hostvol_file_spec_][-dG_DG_NAME_][-fstype_type_][-vmtype_type_]`

ディスク・グループを作成するには、次の形式を使用します。 `-dG_DG_NAME_[-fstype_type] [-vmtype_type_]]

====


 a| 
つながる
 a| 
SnapDrive storage connect -fs_file_name -nolvm --lun_long_lun_name_[-igroup _ig_name _[_dig_name ..._]] [-nopersist] [-mntopts options] [-deviceType ｛ shared | dedided] [-fstype_type_type_] [--fsttype_type_type_type_type] [-f]



 a| 
SnapDrive storage connect -fs_file_name _spec_-hostvol_file_dspec_-lun_long_lun_name_[_lun_name_name..._][-igroup _ig_name_[_ig_name..._]] [-nopersist] [-mntopts options] [-deviceType ｛ share|dedicated] [-fsttype] [-fsttype] [ft_sype] [-ftype



 a| 
SnapDrive storage connect -lun_long_lun_name_[_lun_name_..][-igroup _ig_name_[_dig_name..._]] [-vmtype_type_]]



 a| 
SnapDrive ストレージ接続 -lun_long_lun_name_[_lun_name..._][-deviceType ｛ shared_|dedicated] [-vmtype_type_]]



 a| 
SnapDrive storage connect -fs_file_name _spec_{-hostvol|-lvol }_file_spec_-lun_long_lun_name_[_lun_name..._][-deviceType ｛ shared_}][ -nosist][-mntopts options][-fstype_type_][-vmtype_type_type_type_



 a| 
切断します
 a| 
SnapDrive storage disconnect - lun_long_lun_name_[_lun_name ..._][-deviceType ｛ shared | dedicated ｝ ] [-vmtype_type_]]



 a| 
SnapDrive storage disconnect ｛ -vg | -dg | -fs | -lvol | -hostvol ｝ _file_spec_[_file_spec..._][ ｛ -vg | -dg | -fs | -lvol | -hostvol ｝ _file_spec_… ] ... ] [-full] [-deviceType { shared | dedicated }] [-fstype_type_][-vmtype_type_]]



 a| 
サイズ変更
 a| 
SnapDrive storage resize ｛ -dg | -vg ｝ _file_spec_[_file_spec..._] ｛ -growby | -growto ｝ _size_[____addlun [-igroup_ig_name_[_ig_name...] [{-resesesg_name..._]] [-noreserve }] [-fstype_type] [vmtype



 a| 
表示 / 一覧表示
 a| 
SnapDrive storage ｛ show | list ｝ -fir_filername_[_filername..._][-verbose [-quiet ] [-capabilities]`



 a| 
SnapDrive storage ｛ show | list ｝ -fileervol_long_filer_path_[_filer_path..._][-verbose ] [-quiet ] [-capabilities]`



 a| 
SnapDrive ストレージ {show|list} {-all|device} [-deviceType {shareed|dedicated] [-capabilities]`



 a| 
SnapDrive storage show [-verbose] ｛ -firer_filername_[_filername..._]|-filervol_volname_[_volname..._]} [-deviceType ｛ shareed|dedicated] [-capabilities]`



 a| 
SnapDrive storage ｛ show | list ｝ -lun_long_lun_name _[_lun_name ..._][-verbose ] [-quiet ] [-status] [-capabilities]



 a| 
SnapDrive storage ｛ show | list ｝ ｛ -vg|-dg|-fs|-lvol|-hostvol ｝ _file_spec_[_file_spec..._][｛ -vg|-fs|-lvol|-hostvol ｝ _file_spec_[_file_spec...] [-verbose ] [-dosquiet] [vmtype] [-dose] [-dose] [d



 a| 
SnapDrive ストレージ ｛ show | list ｝ ｛ -fir_filer_name_[_filer_name_path_[_filer_path...] ｝ [-verbose ] [-deviceType ｛ shared | dedicated ｝ ] [-capabilities] [-quiet ]



 a| 
SnapDrive storage ｛ show | list ｝ -lun_long_lun_name _[_lun_name … _][-verbose ][-verbose ] [-status] [-fstype_type_] [-vmtype_type_] [-capabilities] [-quiet ]



 a| 
削除
 a| 
SnapDrive storage delete [-lun]_long_lun_name_[_lun_name..._][-deviceType ｛ shared_|ded}][-fstype_type_][-vmtype_type_]`



 a| 
SnapDrive storage delete [-vg | -dg | -fs|-lvol | -hostvol]_file_spec_[_file_dspec..._][｛ -vg | -dg | -fs|-lvol | -hostvol ｝ _file_spec_[_file_spec...] [-full] [-deviceType { shared | dedicated }]] [-fstype_type_][-vmtype_type_]]

|===
* 関連情報 *

xref:reference_command_line_arguments.adoc[コマンドライン引数]
