---
permalink: solaris/reference_exit_status_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, exit, status, value 
summary: 各終了ステータス値には、エラー名と、それに関連付けられたタイプがあります。テーブルを表示して、終了ステータス値、エラー名、タイプ、および概要について確認します。 
---
= 終了ステータスの値
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各終了ステータス値には、エラー名と、それに関連付けられたタイプがあります。テーブルを表示して、終了ステータス値、エラー名、タイプ、および概要について確認します。

次の表に、終了ステータスの値を示します。終了ステータスの値には、順番に番号が付けられます。SnapDrive for UNIX が現在エラーを実装していない場合、この終了ステータスの値はテーブルに含まれません。その結果、数値にギャップが生じる場合があります。

|===
| 終了値 | エラー名 | を入力します | 説明 


 a| 
1.
 a| 
サポート対象外
 a| 
コマンドエラー
 a| 
このバージョンの SnapDrive for UNIX ではサポートされていない関数が呼び出されました。



 a| 
2.
 a| 
メモリがありません
 a| 
致命的
 a| 
システムのメモリが不足しています。SnapDrive for UNIX は、十分なメモリを解放しないと動作しません。実行中の他のアプリケーションを調べて、過剰なメモリを消費していないことを確認します。



 a| 
3.
 a| 
無効なコマンドです
 a| 
コマンドエラー
 a| 
無効なコマンドを発行しました。これは、入力したコマンドのテキストに構文エラーがある可能性があります。



 a| 
4.
 a| 
はすでに存在します
 a| 
コマンドエラー
 a| 
すでに存在するものを作成するよう要求しました。通常、このエラーは、 Snapshot コピーの名前を指します。この名前は、 Snapshot コピーを作成するストレージシステムボリュームには存在しない名前にする必要があります。



 a| 
5.
 a| 
スレッドの作成に失敗しました
 a| 
管理エラー
 a| 
SnapDrive for UNIX はプロセススレッドを作成できませんでした。システムで実行されている他のプロセスを調べて、十分なスレッドリソースが使用可能であることを確認します。



 a| 
6.
 a| 
が見つかりません
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX のコマンドラインに、ファイル、データグループ、ホストボリューム、ファイルシステム、またはその他の引数が存在しない場合は、それらを入力します。



 a| 
7.
 a| 
マウントされたファイルシステムではありません
 a| 
コマンドエラー
 a| 
アクセスするファイルシステムが有効なファイルシステムでないか、マウントされていません。



 a| 
9.
 a| 
ボリュームマネージャのエラーです
 a| 
コマンドエラー
 a| 
ボリュームマネージャへのアクセス時にエラーが返されました。エラーの詳細およびその理由については、特定のエラーメッセージを参照してください。



 a| 
10.
 a| 
名前が無効です
 a| 
コマンドエラー
 a| 
コマンドラインに、正しくフォーマットされていない名前を入力しました。

たとえば、ストレージ・システム・ボリュームが「 filer ： /vol/vol_name 」として指定されていません。また、ストレージシステムまたはボリュームマネージャベースの名前に無効な文字が含まれている場合にも表示されます。



 a| 
11.
 a| 
デバイスが見つかりません
 a| 
管理エラー
 a| 
SnapDrive for UNIX は、 Snapshot コピーを作成するディスクグループ内の LUN にはアクセスできません。

ホストとストレージ・システムの両方で、すべての LUN のステータスを確認します。また、ストレージ・システム・ボリュームがオンラインであること、およびストレージ・システムが稼働していてホストに接続されていることを確認します。



 a| 
12.
 a| 
ビジーです
 a| 
コマンドエラー
 a| 
LUN デバイス、ファイル、ディレクトリ、ディスクグループ、ホストボリューム、 または他のエンティティがビジーです。

これは、通常はコマンドを再試行するときに発生する致命的でないエラーです。リソースまたはプロセスがハングし、 SnapDrive for UNIX でオブジェクトがビジー状態になって使用できなくなっていることを示す場合があります。

また、 I/O トラフィックの負荷が高くなりすぎて Snapshot コピーを正常に作成できないときに、 Snapshot コピーを作成しようとしている可能性もあります。



 a| 
13
 a| 
初期化できません
 a| 
致命的
 a| 
SnapDrive for UNIX は、必要なサードパーティの資料を初期化できませんでした。これは、ファイルシステム、ボリュームマネージャ、ホストクラスタソフトウェア、マルチパスソフトウェアなどです。



 a| 
14
 a| 
SnapDrive がビジーです
 a| 
SnapDrive がビジーです
 a| 
別のユーザまたはプロセスが、 SnapDrive で処理を実行するように要求したのと同時に、同じホストまたはストレージシステム上で処理を実行しています。処理を再試行してください。

このメッセージは、他のプロセスがハングしたことを意味し、強制終了する必要がある場合があります。


NOTE: 状況によっては、 Snapshot のリストア処理に時間がかかることがあります。ハングしたと思われるプロセスが、 Snapshot のリストア処理が完了するのを待機しているだけではないことを確認します。



 a| 
15
 a| 
構成ファイルのエラーです
 a| 
致命的
 a| 
snapdrive.conf ファイルのエントリが無効、不適切、または整合性がない。詳細については、該当するエラーメッセージを参照してください。SnapDrive for UNIX を続行するには、このファイルを修正する必要があります。



 a| 
17
 a| 
権限が無効です
 a| 
コマンドエラー
 a| 
このコマンドを実行する権限がありません。SnapDrive for UNIX を実行するには、 root としてログインする必要があります。



 a| 
18
 a| 
ストレージシステムがありません
 a| 
管理エラー
 a| 
SnapDrive for UNIX は、このコマンドに必要なストレージシステムにアクセスできません。エラーメッセージに示されたストレージシステムへの接続を確認してください。



 a| 
19
 a| 
ファイラーログインが正しくありません
 a| 
管理エラー
 a| 
指定したログイン情報を使用して SnapDrive for UNIX からストレージシステムにログインすることはできません。



 a| 
20
 a| 
ライセンスが無効です
 a| 
管理エラー
 a| 
このストレージシステム上で実行するには、サービス SnapDrive for UNIX のライセンスが必要です。



 a| 
22
 a| 
fs をフリーズできません
 a| 
管理エラー
 a| 
SnapDrive for UNIX で、 Snapshot コピーを作成するために指定されたファイルシステムをフリーズできなかったため、 Snapshot の作成処理に失敗しました。ファイルシステムをフリーズするのに十分な I/O トラフィックが少ないことを確認してから、コマンドを再試行してください。



 a| 
27
 a| 
整合性のない Snapshot コピーです
 a| 
管理エラー
 a| 
ディスクグループのイメージに整合性がない Snapshot コピーからのリストアが要求されたため、 Snapshot のリストア処理に失敗しました。整合性のない画像は、次の場合に発生する可能性があります。

* SnapDrive for UNIX を使用して Snapshot コピーを作成していない。
* Snapshot 作成処理は、整合性のあるビットが設定される前に中断されたため、（重大なシステム障害の場合のように）クリーンアップできませんでした。
* 作成後に Snapshot コピーで何らかのデータの問題が発生しました。




 a| 
28
 a| 
HBA 障害です
 a| 
管理エラー
 a| 
SnapDrive for UNIX で、 HBA から情報を取得しようとしてエラーが発生しました。



 a| 
29
 a| 
メタデータが無効です
 a| 
管理エラー
 a| 
SnapDrive for UNIX で、 Snapshot コピーの作成時に書き込んだ Snapshot コピーメタデータにエラーが発生しました。



 a| 
30
 a| 
Snapshot コピーのメタデータがありません
 a| 
管理エラー
 a| 
メタデータに要求されたディスクグループが一部含まれていないため、 SnapDrive for UNIX では Snapshot リストア処理を実行できません。



 a| 
31.
 a| 
パスワードファイルが正しくありません
 a| 
管理エラー
 a| 
パスワードファイルのエントリが正しくありません。このストレージ・システムのログイン・エントリを削除するには、 SnapDrive config delete コマンドを使用します。次に '_SnapDrive config setuser_name コマンドを使用して ' ログイン情報を再入力します



 a| 
33
 a| 
パスワードファイルのエントリがありません
 a| 
管理エラー
 a| 
パスワードファイルにこのストレージシステム用のエントリがありません。SnapDrive for UNIX を実行する必要のあるすべてのストレージ・システムに対して '_unix SnapDrive config setUserName filername_` コマンドを実行しますその後、もう一度この処理を実行してください。



 a| 
34
 a| 
NetAPPLUN ではありません
 a| 
管理エラー
 a| 
SnapDrive for UNIX コマンドで、ネットアップストレージシステムにない LUN が検出されました。



 a| 
35
 a| 
ユーザは中止されました
 a| 
管理エラー
 a| 
処理の確認を求めるプロンプトが表示され、処理を実行する必要がないことを確認できます。



 a| 
36
 a| 
I/O ストリームエラー
 a| 
管理エラー
 a| 
システム入力ルーチンまたはシステム出力ルーチンが、 SnapDrive for UNIX が認識しなかったエラーを返しました。

snapdrive .dc を実行し、その情報をネットアップテクニカルサポートに送信して、リカバリを完了するために実行する手順を決定します。



 a| 
37
 a| 
ファイルシステムがいっぱいです
 a| 
管理エラー
 a| 
ファイルシステムに十分なスペースがないため、ファイルの書き込みが失敗しました。適切なファイルシステムに十分なスペースが解放されていれば、 SnapDrive for UNIX の処理を続行できます。



 a| 
38
 a| 
ファイルエラー
 a| 
管理エラー
 a| 
SnapDrive for UNIX がシステム構成ファイルまたは一時ファイルの読み取りまたは書き込みを行っているときに、 I/O エラーが発生しました。



 a| 
39
 a| 
重複するディスクグループです
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX でディスクグループをアクティブ化しようとすると、重複するマイナーノード番号が取得されました。



 a| 
40
 a| 
ファイルシステムの解凍に失敗しました。
 a| 
管理エラー
 a| 
ファイルシステム上のシステムアクティビティにより、 snap create コマンドが失敗しました。通常この問題は、 SnapDrive for UNIX ファイルシステムがフリーズしたときに、 Snapshot コピーの作成に必要となり、 Snapshot コピーが完了する前にタイムアウトになります。



 a| 
43
 a| 
この名前はすでに使用されています
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX は、ディスクグループ、ホストボリューム、ファイルシステム、または LUN の作成を試みましたが、すでに名前が使用されています。修正するには、使用していない名前を選択し、 SnapDrive for UNIX コマンドを再入力します。



 a| 
44
 a| 
ファイルシステムマネージャのエラーです
 a| 
致命的
 a| 
SnapDrive for UNIX で、次の場合にファイルシステムから予期しないエラーが発生しました：

* ファイルシステムを作成しようとしています
* ファイルシステムのマウントテーブルにエントリを作成し、ブート時にファイルシステムを自動的にマウントします。


このコードと共に表示されるエラーメッセージのテキストは、ファイルシステムで発生したエラーを示しています。リカバリを完了するための手順を判断できるように、メッセージを記録してネットアップテクニカルサポートに送信します。



 a| 
45
 a| 
マウントポイントエラー
 a| 
管理エラー
 a| 
ファイルシステムマウントポイントがシステムマウントテーブルファイルに表示されました。修正するには、使用中でないマウントポイントまたはマウントテーブルに含まれているマウントポイントを選択し、 SnapDrive for UNIX コマンドを再入力します。



 a| 
46
 a| 
LUN が見つかりません
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX コマンドが、ストレージ・システム上に存在しなかった LUN にアクセスしようとしました。

正しく設定するには、 LUN が存在すること、および LUN 名が正しく入力されていることを確認します。



 a| 
47
 a| 
イニシエータグループが見つかりません
 a| 
管理エラー
 a| 
ストレージシステムのイニシエータグループに想定どおりアクセスできませんでした。そのため、 SnapDrive for UNIX では現在の処理を完了できません。

具体的なエラーメッセージには、問題の内容と解決に必要な手順が記載されています。問題を修正してからコマンドをもう一度実行してください。



 a| 
48
 a| 
オブジェクトはオフラインです
 a| 
管理エラー
 a| 
SnapDrive for UNIX は、オブジェクト（ボリュームなど）へのアクセスを試みましたが、オブジェクトがオフラインであるために失敗しました。



 a| 
49
 a| 
競合するエンティティ
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX で igroup の作成が試行されましたが、同じ名前の igroup が見つかりました。



 a| 
50
 a| 
クリーンアップエラーです
 a| 
致命的
 a| 
SnapDrive for UNIX で、削除する必要がある項目が検出されましたが、まだ存在しています。



 a| 
51
 a| 
ディスクグループ ID が競合しています
 a| 
コマンドエラー
 a| 
SnapDrive snap connect コマンドは ' 既存のディスク・グループと競合するディスク・グループ ID を要求しました

これは通常、元のホスト上の SnapDrive snap connect コマンドが、それをサポートしていないシステム上で試行されることを意味します。この問題を解決するには、別のホストから処理を実行してください。



 a| 
52
 a| 
LUN がどのホストにもマッピングされていません
 a| 
管理エラー
 a| 
LUN はどのホストにもマッピングされていません。つまり、このボリュームはストレージシステムのイニシエータグループに属していません。アクセスできるようにするには、 SnapDrive for UNIX の外部にある現在のホストに LUN をマッピングする必要があります。



 a| 
53
 a| 
LUN がローカルホストにマッピングされていません
 a| 
管理エラー
 a| 
LUN は現在のホストにマッピングされていません。つまり、現在のホストのイニシエータを含むストレージシステムのイニシエータグループには属しません。アクセスできるようにするには、 SnapDrive for UNIX の外部にある現在のホストに LUN をマッピングする必要があります。



 a| 
54
 a| 
LUN は外部 igroup を使用してマッピングされています
 a| 
管理エラー
 a| 
LUN は外部ストレージシステムのイニシエータグループを使用してマッピングされます。つまり、ローカルホスト上にないイニシエータのみを含むストレージシステム igroup に属していることになります。

そのため、 SnapDrive for UNIX では LUN を削除できません。

SnapDrive for UNIX を使用して LUN を削除するには、その LUN がローカル igroup 、つまりローカルホストで検出されたイニシエータのみを含む igroup にのみ属している必要があります。



 a| 
55
 a| 
LUN は、混在 igroup を使用してマッピングされます
 a| 
管理エラー
 a| 
LUN は、混在ストレージシステムのイニシエータグループを使用してマッピングされます。つまり、ローカルホストで検出された両方のイニシエータを含むストレージシステム igroup に属していて、イニシエータが見つかりません。

このため、 SnapDrive for UNIX では LUN を切断できません。

SnapDrive for UNIX を使用して LUN を切断するには、その LUN がローカル igroup または外部 igroup にのみ属していて、混在 igroup には属していない必要があります。（ローカル igroup には、ローカルホストで検出されたイニシエータのみが含まれています。外部 igroup には、ローカルホストで検出されなかったイニシエータが含まれています）



 a| 
56
 a| 
Snapshot コピーのリストアに失敗しました
 a| 
管理エラー
 a| 
SnapDrive for UNIX は、 Snapshot リストア処理を試行しましたが、 Snapshot コピーに LUN が含まれていない状態で失敗しました。

具体的なエラーメッセージには、問題の内容と解決に必要な手順が記載されています。問題を修正してからコマンドをもう一度実行してください。



 a| 
58
 a| 
ホストのリブートが必要です
 a| 
管理エラー
 a| 
内部データを更新するには、ホストオペレーティングシステムをリブートする必要があります。SnapDrive for UNIX では、この更新のためにホストが準備されていますが、現在の処理を完了できません。

ホストをリブートしてから、このメッセージが表示されるようにする SnapDrive for UNIX コマンドラインを再入力してください。リブートが完了すると、処理を完了できるようになります。



 a| 
59
 a| 
ホスト、 LUN の準備が必要です
 a| 
管理エラー
 a| 
現在の処理を完了するには、ホストオペレーティングシステムで内部データを更新する必要があります。この更新は、新しい LUN を作成できるようにするために必要です。

SnapDrive for UNIX は ' プロビジョニングの自動ホスト準備が無効になっているため ' 更新を実行できませんこれは 'napdrive.conf 変数 _enable-implicit-host-preparation_' がオフに設定されているためです

ホストの自動準備を無効 SnapDrive にした場合は、 lun config prepare LUN' コマンドを使用して、 LUN をプロビジョニングするホストを準備するか、または手動で準備手順を実行する必要があります。

このエラー・メッセージが表示されないようにするには 'napdrive.conf ファイルで '_enable-implicit-host-preparation_' の値を "`on ’に設定します



 a| 
62
 a| 
空ではありません
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX がストレージ・システム・ボリュームまたはディレクトリを削除できなかったため、エラーが発生しました。この問題は、別のユーザまたはプロセスが、 SnapDrive が削除しようとするファイルをまったく同じ時刻と同じディレクトリに作成した場合に発生することがあります。このエラーを回避するには、一度にストレージ・システム・ボリュームを使用するユーザが 1 人だけであることを確認してください。



 a| 
63
 a| 
タイムアウトが切れました
 a| 
コマンドエラー
 a| 
SnapDrive for UNIX が 50 分以内に LUN をリストアできなかったため、エラーが発生しました。

リカバリを完了するための手順を判断できるように、メッセージを記録してネットアップテクニカルサポートに送信します。



 a| 
64
 a| 
サービスが実行されていません
 a| 
管理エラー
 a| 
NFS エンティティを指定した SnapDrive for UNIX コマンドで、ストレージシステムが NFS サービスを実行していないため、エラーが発生しました。



 a| 
126
 a| 
不明なエラーです
 a| 
管理エラー
 a| 
重大な不明なエラーが発生しました。「 napdrive.dc 」ユーティリティを実行し、その結果を分析のためにネットアップのテクニカルサポートに送信します。



 a| 
127
 a| 
内部エラー
 a| 
致命的
 a| 
SnapDrive for UNIX の内部エラーが発生しました。「 napdrive.dc 」を実行し、その結果を分析のためにネットアップのテクニカルサポートに送信します。

|===