---
permalink: solaris/reference_command_line_keywords.html 
sidebar: sidebar 
keywords: snap, snapdrive, command, line, keywords 
summary: SnapDrive for UNIX では、キーワードを使用して、ホストディスクグループ、デスティネーショングループ、ボリューム、または FlexClone 、 NFS ファイル、 ストレージシステムなど。 
---
= コマンドラインキーワード
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX では、キーワードを使用して、ホストディスクグループ、デスティネーショングループ、ボリューム、または FlexClone 、 NFS ファイル、 ストレージシステムなど。

ここでは、 SnapDrive for UNIX コマンドで使用できるキーワードを示します。これらのコマンドを使用して、 SnapDrive for UNIX 操作のターゲットを指定します。これらのキーワードには、 1 つ以上の引数を指定できます。


NOTE: LVM の中にはディスクグループを表し、ボリュームグループを表しているものもあります。SnapDrive for UNIX では、これらの用語は同義語として扱われます。また、 LVM の中には論理ボリュームを表し、ボリュームを表しているものもあります。SnapDrive for UNIX では、ホストボリューム（ストレージシステムボリュームとホスト論理ボリュームの混同を防ぐために作成されたボリューム）という用語と論理ボリュームを同義語として使用します。

|===
| キーワード | このキーワードで使用する引数 


 a| 
dg ( 「 -vg` 」と同義 )
 a| 
ホストディスクグループの名前。このオプションを使用して、ディスクグループまたはボリュームグループの名前を入力できます。



 a| 
-destddd`

「 -desthv 」と入力します

-destlv`

-destvg`
 a| 
デスティネーショングループまたはボリューム。



 a| 
-destfv`
 a| 
SnapDrive for UNIX によって NFS Snapshot 接続処理中に作成されるボリュームクローンをコマンドラインで指定した FlexClone ボリュームの名前。


NOTE: この引数は NFS ボリュームのみをサポートし、 NFS ディレクトリはサポートしません。



 a| 
「 -file' 」と入力します
 a| 
NFS ファイルの名前。



 a| 
「 -ffiler」 のように指定します
 a| 
ストレージシステムの名前。



 a| 
`-filervol`
 a| 
ストレージシステムおよびそのボリュームの名前。



 a| 
`-fs`
 a| 
ホスト上のファイルシステムの名前。使用される名前は、ファイルシステムが現在マウントされているディレクトリ、またはマウントされるディレクトリ（マウントポイント）です。



 a| 
「 -hostvol 」または「 -lvol 」
 a| 
ホストボリューム名。ホストボリュームが含まれているディスクグループも含まれます。たとえば 'large_vg/accounting_lvol' と入力します



 a| 
「 -igroup 」と入力します
 a| 
イニシエータグループ（ igroup ）の名前。

ターゲットストレージシステムで igroup を指定する代わりに、 SnapDrive for UNIX で作成されるデフォルトの igroup を使用することを強く推奨します。デフォルトの igroup は、 HOSTNAME_PROTOP_SdIg です。

* `_hostname_` は現在のホストのローカル ( ドメイン修飾されていない ) 名です
* `_protocol_` はホストが使用しているプロトコルに応じて 'fcp` または 'iSCSI' のいずれかです


igroup hostname_protocol_sdIg が存在しない場合は、 SnapDrive for UNIX によって作成され、ホストのすべてのイニシエータがこの igroup に格納されます。

イニシエータが存在し、そのイニシエータが正しい場合、 SnapDrive for UNIX は既存の igroup を使用します。

igroup が存在するが、このホストのイニシエータが含まれていない場合、 SnapDrive for UNIX は別の名前で新しい igroup を作成し、現在の処理でその igroup を使用します。同じ名前が使用されないように、 SnapDrive for UNIX では、新しい名前の作成時に一意の番号が割り当てられます。この場合、名前の形式は hostname -number_protocol_sdIg です。

独自の igroup 名を指定すると、 SnapDrive for UNIX では igroup の内容が検証されません。これは、ホストに対応する igroup がストレージシステム上に存在するかどうかを IT 部門が常に判別できないためです。

イニシエータグループを指定する際にこのオプションを使用するすべてのコマンドは、共有ディスクグループとファイルシステムでは使用できません。このオプションは、ローカルリソースに対してのみ使用できます。

--deviceType 共有オプションを有効にしている場合、このオプションは使用できません。これは、「 -igroup 」オプションがローカルリソースに対してのみ有効であり、共有リソースに対しては有効ではないためです。igroup の指定の詳細については、 SnapDrive for UNIX のマニュアルページを参照してください。

外部 igroup がコマンドラインに含まれている場合、 SnapDrive for UNIX コマンドは失敗します。コマンドラインで指定したすべての igroup に、ローカルホストのイニシエータが含まれていることを確認してください。



 a| 
「 -lun' 」と入力します
 a| 
ストレージシステム上の LUN の名前。このキーワードに指定する最初の LUN 名には、完全パス名（ストレージシステム名、ボリューム名、および LUN 名）を指定する必要があります。追加の LUN 名については、ボリューム内の名前のみを指定するか（ボリュームを変更しない場合）、新しいストレージシステム名または新しいボリューム名を指定するパスを指定できます（ボリュームの切り替えのみを行う場合）。


NOTE: SnapDrive snap connect コマンドでは '_lun_name は 'lun_name' または 'tree_name/lun_name の形式にする必要があります



 a| 
「 -lvol 」または「 -hostvol 」
 a| 
論理ボリューム名。含まれているボリュームグループも含みます。たとえば ' 論理ボリューム名として large_vg/accounting_lvol' と入力します



 a| 
` - snapname
 a| 
Snapshot コピーの名前。



 a| 
「 -vg` 」または「 -dg` 」
 a| 
ボリュームグループの名前。このオプションを使用して、ディスクグループまたはボリュームグループの名前を入力できます。

|===