---
permalink: solaris/reference_command_line_options.html 
sidebar: sidebar 
keywords: snap, snapdrive, command, line, options 
summary: SnapDrive for UNIX コマンドでは、さまざまなオプションを使用できます。 
---
= コマンドラインオプション
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX コマンドでは、さまざまなオプションを使用できます。

SnapDrive for UNIX では、コマンドに応じて次のオプションを指定できます。場合によっては、これらのオプションを省略できます。たとえば、「 -help 」ではなく「 -h 」を使用できます。

|===
| オプション | 説明 


 a| 
「 -addlun 」を参照してください
 a| 
SnapDrive for UNIX で、サイズを拡張するために、内部で生成された新しい LUN をストレージエンティティに追加するように指示します。



 a| 
` - すべて」
 a| 
SnapDrive storage '{show|list}' コマンドとともに使用して ' ホストで認識されているすべてのデバイスおよび LVM エンティティを表示します



 a| 
-- 自動展開
 a| 
SnapDrive snap connect コマンドとともに使用することにより ' ディスク・グループ内の論理ボリュームまたはファイル・システムのサブセットを提供するときに ' ディスク・グループの接続を要求できます



 a| 
`-autorname`
 a| 
SnapDrive snap connect コマンドとともに使用して ' デフォルト名がすでに使用されている新たに接続された LVM エンティティの名前を変更するコマンドを有効にします



 a| 
「 clone type 」と入力します
 a| 
clone - 'snap connect' 操作中に使用するメソッドここでは、 lunclone （ LUN クローンの作成）、 Optimal （ストレージ構成に応じて、 SnapDrive によって制限のある FlexClone と LUN クローンが自動的に選択される）、 Unrestricted （作成される FlexClone ）の 2 つのタイプを示します。これらの FlexClone は、通常のフレキシブルボリュームと同様にプロビジョニング処理と Snapshot 処理に使用できます。



 a| 
- 「アパビリティー」
 a| 
SnapDrive storage show コマンドとともに使用して ' ホスト・ファイルの仕様で許可されている操作を確認します



 a| 
「 -devices 」または「 -dev 」です
 a| 
ホストが認識しているすべてのデバイスを表示するには 'storage '{show|list}' コマンドとともに使用します



 a| 
`-deviceType`
 a| 
SnapDrive for UNIX の操作に使用するデバイスのタイプを指定します。このオプションの値は次のとおりです。

* 'shared' ：ホスト・クラスタとしての LUN ' ディスク・グループ ' およびファイル・システムのスコープを指定します
* d`edicated -- LUN 、ディスクグループ、およびファイルシステムの範囲をローカルとして指定します。これがデフォルト値です。


このオプションをサポートする UNIX コマンド用の SnapDrive で '-deviceType' オプションを指定しない場合は '-deviceType dedicated と同じになります



 a| 
`-dgsize` または -vgsize`
 a| 
SnapDrive storage create コマンドとともに使用して ' 作成するディスク・グループのサイズをバイト単位で指定します



 a| 
「 -force 」（または「 -f 」）
 a| 
SnapDrive for UNIX が通常どおり実行しない操作を試行します。SnapDrive for UNIX では、処理の実行前に確認を求めるプロンプトが表示されます。



 a| 
「 -fsopts 」
 a| 
新しいファイルシステムを作成するホスト処理に渡すオプション。ホスト OS によっては、このホスト操作は「 mkfs 」コマンドのようなコマンドになる場合があります。

このオプションで指定する引数は、通常、引用符で囲んだ文字列として指定する必要があり、コマンドに渡す正確なテキストを含める必要があります。

たとえば ' ホスト操作に渡すオプションとして '-o largefiles' を入力します



 a| 
「 -fstype 」を入力します
 a| 
SnapDrive for UNIX の処理に使用するファイルシステムのタイプ。ファイルシステムは、 SnapDrive for UNIX でサポートされているオペレーティングシステムのタイプである必要があります。この変数に設定できる現在の値はです

また '-fstype' 構成変数を使用して ' 使用するファイル・システムのタイプを指定することもできます



 a| 
「 -full` 」
 a| 
指定したホスト側のエンティティに対して、空でない場合でも処理を実行できます（たとえば、 1 つ以上の論理ボリュームを含むボリュームグループなど）。



 a| 
` - 生産者」
 a| 
LUN またはディスクグループに追加してサイズを拡張するバイト数。



 a| 
「 -growto 」
 a| 
LUN 、ディスクグループ、またはボリュームグループのターゲットサイズ（バイト）。SnapDrive for UNIX は、ターゲットサイズに達するために必要なバイト数を自動的に計算し、そのバイト数分だけオブジェクトのサイズを増やします。



 a| 
` -- 助け」
 a| 
コマンドおよび操作の使用状況を示すメッセージを出力します。他のオプションを指定せずに、このオプションだけを入力します。コマンドラインの例を次に示します。



 a| 
「 -lunsize 」と入力します
 a| 
指定したコマンドで作成される LUN のサイズ（バイト）。



 a| 
「 -mntopts 」と入力します
 a| 
host mount コマンドに渡すオプションを指定します（たとえば、ファイルシステムのロギング動作を指定します）。オプションは、ホストファイルシステムのテーブルファイルにも保存されます。指定できるオプションは、ホストファイルシステムのタイプによって異なります。

指定する「 -mntopts 」引数は、「 m ount 」コマンド「 `-o ` 」フラグで指定されたファイルシステムタイプオプションです。「 -mntopts 」引数に「 -o`」 フラグを含めないでください。たとえば '-mntopts_tmplog_ というシーケンスは ' 文字列 '-o_tmplog_ をマウントコマンドラインに渡し ' 新しいコマンドラインにテキスト "tmplog`" を挿入します



 a| 
`-nofilerfenc`
 a| 
複数のストレージシステムボリュームにまたがる Snapshot コピーの作成時に、 Data ONTAP 整合グループ機能の使用を抑制します。

Data ONTAP 7.2 以降では、 Filer ボリューム全体へのアクセスを中断できます。-nofilerfence-オプション を使用すると、個々の LUN へのアクセスをフリーズできます。



 a| 
「 -nolvm 」と入力します
 a| 
ホスト LVM を使用せずに、 LUN 上で直接ファイルシステムを接続または作成します。

LUN 上でファイルシステムを直接接続または作成する場合にこのオプションを使用するすべてのコマンドは、ホストクラスタや共有リソースに対してこのオプションを使用することはできません。このオプションは、ローカルリソースに対してのみ使用できます。-deviceType 共有オプションを有効にした場合 ' このオプションは使用できませんこれは '-nolvm' オプションがローカルリソースに対してのみ有効であり ' 共有リソースに対しては有効ではないためです



 a| 
「 -nopersist` 」
 a| 
ホストの永続的マウントエントリファイルにエントリを追加せずに、ファイルシステムまたはファイルシステムを含む Snapshot コピーを接続または作成します。



 a| 
`-prefix fv`
 a| 
クローニングされたボリューム名の生成時に使用するプレフィックス。新しいボリュームの名前の形式は、「 <pre-fix>_ <original_volume_name >` 」です。



 a| 
「 -reserve-noreserve 」を適用します
 a| 
SnapDrive storage create 'unix snap connect'or SnapDrive snap restore' コマンドと併用 SnapDrive して 'UNIX 用の SnapDrive でスペース・リザベーションを作成するかどうかを指定しますデフォルトでは、 SnapDrive for UNIX は storage create 、 resize 、および Snapshot create の処理用に予約を作成し、 Snapshot 接続処理の予約は作成しません。



 a| 
-noprompt`
 a| 
コマンド実行中にプロンプトを表示しません。デフォルトでは、危険な操作や直感的でない操作を行うと、 SnapDrive for UNIX の実行を確認するように求められます。このオプションは ' そのプロンプトを上書きします -force オプションと組み合わせると 'UNIX の SnapDrive は確認を求めずに操作を実行します



 a| 
「 -quiet 」（または「 -q 」）
 a| 
エラーや警告のレポートを、正常か診断的かに関係なく抑制します。0 （成功）または 0 以外のステータスが返されます。「 -quiet 」オプションは「 -verbose 」オプションを上書きします。

このオプションは、 SnapDrive storage show コマンド、 SnapDrive snap show コマンド、および SnapDrive config show コマンドでは無視されます。



 a| 
「 -readonly 」
 a| 
Data ONTAP 7.1 またはトラディショナル・ボリュームを使用するすべての構成に必要です。NFS ファイルまたはディレクトリを読み取り専用アクセスで接続します。

FlexVol 7.0 で Data ONTAP ボリュームを使用する構成の場合はオプションです。NFS ファイルまたはディレクトリツリーを読み取り専用アクセスで接続します。（デフォルトは読み書き）。



 a| 
「 -split` 」
 a| 
Snapshot 接続処理と Snapshot 切断処理の際に、クローンボリュームまたは LUN をスプリットできます。

また '_enable-split-clone_' 構成変数を使用して ' クローン・ボリュームまたは LUN をスプリットすることもできます



 a| 
「 -status` 」と入力します
 a| 
SnapDrive storage show コマンドとともに使用して、ボリュームまたは LUN のクローンが作成されているかどうかを確認します。



 a| 
` - 無関係」
 a| 
Snapshot コピーが作成されるときに従属書き込みを持たない '_file_spec_' エンティティのスナップショット・コピーを作成しますエンティティには従属書き込みがないため、 SnapDrive for UNIX は個々のストレージエンティティの crash-consistent Snapshot コピーを作成しますが、エンティティ同士の整合性を保つための手順はありません。



 a| 
「 -verbose 」（または「 -v 」）
 a| 
必要に応じて詳細な出力を表示します。このオプションは、一部のコマンドと処理では無視されますが、すべてのコマンドと処理で受け入れられます。



 a| 
「 -vgsize 」または「 -dgsize 」
 a| 
「 storage create 」コマンドで、作成するボリュームグループのサイズをバイト単位で指定します。



 a| 
「 -vmtype 」と入力します
 a| 
SnapDrive for UNIX の処理に使用するボリュームマネージャのタイプ。

ユーザがコマンド・ラインで -vmtype オプションを明示的に指定した場合 'vmtype 構成変数で指定された値に関係なく SnapDrive for UNIX はオプションで指定された値を使用しますコマンド・ライン・オプションで -vmtype オプションが指定されていない場合 'UNIX 用 SnapDrive は構成ファイル内のボリューム・マネージャを使用します

ボリュームマネージャは、 SnapDrive for UNIX でサポートされているオペレーティングシステムのタイプである必要があります。この変数に VxVM として設定できる現在の値

vmtype 構成変数を使用して、使用するボリュームマネージャのタイプを指定することもできます。



 a| 
`-vbsr {preview|execute}`
 a| 
「 preview 」オプションを使用すると、指定したホスト・ファイル仕様に対して、ボリューム・ベースの SnapRestore プレビュー・メカニズムが開始されます。「 execute 」オプションを指定すると、 SnapDrive for UNIX は、指定されたファイル仕様のボリューム・ベースの SnapRestore で処理を行います。

|===