---
permalink: solaris/task_estimating_the_storage_space_to_split_a_lun_clone.html 
sidebar: sidebar 
keywords: snap, snapdrive, estimate, storage, split, lun, clone 
summary: クローンスプリットの推定によって、 LUN クローンをスプリットするために必要なストレージスペース（ MB ）を見積もることができます。SnapDrive for UNIX が提供するクローンスプリットの推定に応じて、 LUN クローンをスプリットできるスペースを判断できます。 
---
= LUN クローンをスプリットするためのストレージスペースの見積もり
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローンスプリットの推定によって、 LUN クローンをスプリットするために必要なストレージスペース（ MB ）を見積もることができます。SnapDrive for UNIX が提供するクローンスプリットの推定に応じて、 LUN クローンをスプリットできるスペースを判断できます。

.手順
. LUN クローンをスプリットするために必要なストレージスペースを見積もります。
+
`* SnapDrive クローンスプリットの見積もり [-lun]_long_lun_name_[_long_lun_name_name..._]|[{-dg|-vg|-fs|-hostvol|-lvol ｝ _file_spec_[_file_spec..._]|[-snapname_snapname_]|[-volbose.v] -volclone|-verbose |lunv *

+
この処理では、次の情報が表示されます。

+
** リソース名
** Container - LUN クローンのボリューム
** 必要なスペース - LUN クローンをスプリットするために必要なスペース
** 使用可能なスペース - コンテナで使用可能なスペース
** Storage Status - LUN クローンスプリットに使用できるスペースを示します
** Owned Space - LUN クローンが占有しているスペースです
** Shared Space - 親とともに LUN クローンが占有しているスペース


+
「 -verbose( 冗長 ) 」オプションを使用すると、「 Owned Space ( 所有スペース ) 」と「 hared Space ( 共有スペース ) 」が表示されます。



次の例は、 LUN クローンをスプリットするためのストレージスペースを見積もります。

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1
Resource     Container Required Available Storage
                       Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  5120    9986    AVAILABLE
             -112:/vol/vol_1
----
次に '-verbose オプションの使用例を示しますまたは '-v オプションを使用することもできます

[listing]
----
# snapdrive clone split estimate -fs /mnt/my_mnt1 -verbose
Resource    Container  Owned    Shared   Required Available Storage
                       Space(MB)Space(MB)Space(MB)Space(MB) Status
/mnt/my_mnt1 f3050-220  365   403      5120     9986 AVAILABLE
             -112:/vol/vol_1
----