---
permalink: solaris/task_setting_up_an_sfrac_i_o_fencing_environment_on_a_storage_system.html 
sidebar: sidebar 
keywords: snap, snapdrive, sfrac, fencing, environment, storage 
summary: SnapDrive for UNIX では、ストレージプロビジョニングと Snapshot 管理のオプションを使用して、 SFRAC 環境でホストクラスタ全体の共有ディスクグループとノードローカルディスクグループ、およびファイルシステムを管理できます。 
---
= ストレージシステム上で SFRAC I/O フェンシング環境をセットアップする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX では、ストレージプロビジョニングと Snapshot 管理のオプションを使用して、 SFRAC 環境でホストクラスタ全体の共有ディスクグループとノードローカルディスクグループ、およびファイルシステムを管理できます。

.手順
. すべてのホスト・クラスタ・ノードの root ユーザーに対して access-without password-pprompt を使用するには 'rsh' または 'sh' を手動で設定します
+
セットアップ手順については '_Veritas Cluster Server Installation Guide for Solaris_ を参照してください

. ホストクラスタ内のすべてのノードに SnapDrive for UNIX をインストールします。
+
異なるバージョンの SnapDrive for UNIX が異なるノードにインストールされていると、 SnapDrive for UNIX の処理が失敗します。

. ストレージシステム間の FC 接続を確認します。
+
ホストのハードウェア要件については、 SFRAC_Release Notes_ を参照してください。

+

NOTE: すべてのノード上の「 /opt/NTAPsnapdrive/snapdrive.conf 」ファイルのデフォルト転送設定変数は、 FCP に設定されている必要があります。

. ルート・ユーザの「 rsh 」または「パスワードなしのアクセス・プロンプト」がクラスタ内のすべてのノードに対して構成されるようにするには、コンフィギュレーション・変数「 _secure-communication - amining-cluster-nodes _ 」の値を設定します。
+
この値は必須です。ホストクラスタ内の任意のノード（マスターまたは非マスター）から UNIX コマンド用の SnapDrive を開始すると、ホストクラスタ内の他のノードで SnapDrive for UNIX の処理が実行されるためです。

. ホストクラスタの各ノードで次のコマンドを実行して、ホストクラスタノードでのデバイス検出を確認します。
+
`* SnapDrive storage create -lun_long_lun_name _[_lun_name … _] -lunsize [{________-noreserve _}] [igroup ig_name_[_ig_name...] *

+
[listing]
----

	# snapdrive storage create -lun f270-197-109:/vol/vol2/luntest -lunsize 20m

		LUN f270-197-109:/vol/vol2/luntest ... created

		mapping new lun(s) ... done
		discovering new lun(s) ... done

		LUN to device file mappings:
	-f270-197-109:/vol/vol2/luntest => /dev/vx/dmp/c5t0d6s2

	# snapdrive storage delete -lun f270-197-109:/vol/vol2/luntest -lunsize 20m
	- LUN f270-197-109:/vol/vol2/luntest ... deleted
----

