---
permalink: solaris/task_setting_up_access_control_permission.html 
sidebar: sidebar 
keywords: snap, snapdrive, access, control, permission 
summary: SnapDrive for UNIX でアクセス制御権限を設定するには、ストレージシステムのルートボリュームに特別なディレクトリとファイルを作成します。 
---
= アクセス制御権限を設定しています
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapDrive for UNIX でアクセス制御権限を設定するには、ストレージシステムのルートボリュームに特別なディレクトリとファイルを作成します。

root ユーザとしてログインしていることを確認します。

.手順
. ターゲット・ストレージ・システムのルート・ボリュームに「 dprbac 」というディレクトリを作成します。
+
ルートボリュームにアクセスできるようにする方法の 1 つは、 NFS を使用してボリュームをマウントすることです。

. 権限ファイルを 'dbprbac' ディレクトリに作成します次の記述が正しいことを確認してください。
+
** このファイルには 'host-name .prbac' という名前を付ける必要があります host-name は ' アクセス権を指定するホストの名前です
** ファイルは、 SnapDrive for UNIX がそのファイルを読み取ることができるように読み取り専用にする必要がありますが、変更することはできません。


+
dev-sun1 という名前のホストにアクセス権を付与するには ' ストレージ・システム上に次のファイルを作成します `/vol/vol1/sdprbac/sddev-sun1.prbac`

. そのホストのファイルに権限を設定します。
+
ファイルには次の形式を使用する必要があります。

+
** 指定できる権限のレベルは 1 つだけです。ホストにすべての操作へのフルアクセスを許可するには、文字列 all access を入力します。
** 権限の文字列は、ファイルの最初の文字列である必要があります。権限の文字列が 1 行目にない場合、ファイル形式は無効です。
** 権限文字列では大文字と小文字は区別されません。
** アクセス許可文字列の前に空白を追加することはできません。
** コメントは許可されません。
+
これらの有効な権限文字列を使用すると、次のアクセスレベルを設定できます。

** none -- ホストはストレージシステムにアクセスできません
** snap create -- ホストは Snapshot コピーを作成できる。
** スナップの使用 -- ホストは Snapshot コピーを削除したり名前を変更したりできます
** すべてスナップ -- ホストは Snapshot コピーの作成、復元、削除、および名前変更を行うことができます。
** storage create delete -- ホストはストレージの作成、サイズ変更、および削除を行うことができます。
** ストレージ使用量 -- ホストはストレージを接続したり切断したり ' ストレージ上でクローンスプリットの見積もりやクローンスプリットの開始を実行したりすることができます
** Storage All ：ホストは ' ストレージの作成 ' 削除 ' 接続 ' 切断 ' クローン・スプリットの見積もり ' クローン・スプリットの開始をストレージ上で実行できます
** すべてのアクセス -- ホストは 'UNIX で上記のすべての SnapDrive へのアクセス権を持っています
+
これらの各権限文字列は個別です。snap use を指定すると、ホストは Snapshot コピーの削除や名前変更を実行できますが、 Snapshot コピーの作成やリストア、ストレージプロビジョニング処理の実行はできません。

+
設定した権限に関係なく、ホストでは表示とリスト表示の処理を実行できます。



. 次のコマンドを入力して、アクセス権限を確認します。
+
'*SnapDrive config access show_filer_name_*


